theforeman/foreman-ansible-modules

.travis.yml, README.md, modules/foreman_organization.py, modules/katello_product.py, modules/katello_publish.py, modules/katello_repository.py, modules/katello_sync.py, modules/katello_upload.py, requirements.txt
Requires changes from https://github.com/theforeman/foreman-ansible-modules/pull/7
Based on [ansible module devel docs](http://docs.ansible.com/ansible/dev_guide/developing_modules_in_groups.html)
=> Add travis, fix pep8

README.md, modules/foreman_provisioning_template.py, modules/foreman_ptable.py, modules/module_utils/ansible_nailgun_cement.py
@mdellweg and me wrote two modules for creating and maintaining partition and provisioning templates in foreman. They use the nailgun library.
To keep it DRY we factored out some nailgun methods into a separate library.
=> Added modules and utility for partition and provisioning templates

README.md, modules/katello_activation_key.py, test/data/activation-key.json
Requires https://github.com/SatelliteQE/nailgun/pull/419
=> Add katello_activation_key module

test/data/partition-table.json, test/data/provisioning-template.json
This is for use with `hacking/test-module` (debugging).
@Fobhep
=> Add ptemplate/ptable test data

test/demo/activation-keys.yml, test/demo/content-views.yml, test/demo/provisioning_template.yml, test/demo/repositories.yml, test/demo/sync-plans.yml
Now, we can easily do a smoke test on a module with `ansible-playbook test/demo/<module>.yml`
=> Add demo playbooks. Useful for testing/demo.

module_utils/ansible_nailgun_cement.py, modules/katello_manifest.py, test/data/manifest.json, test/demo/manifests.yml
Requires https://github.com/SatelliteQE/nailgun/pull/428
=> Add Katello manifest module

module_utils/ansible_nailgun_cement.py
We think, there was a lot of contribution from @akofink . He should be mentioned.
=> Add contributor to cements author list

module_utils/ansible_nailgun_cement.py, modules/foreman_provisioning_template.py, modules/foreman_ptable.py
As already discussed here https://github.com/theforeman/foreman-ansible-modules/pull/19 with @evgeni 
we (@mdellweg, @fobhep) want to split the present PR19 into two PRs, meaning the PR contains basically the first commit from PR19.
We would need the change upstream in order two prepare a new PR for a new module.
We did some small changes to cement and our preexisting modules two be more specific about entities and lists of entities and handle those more consistent.
=> Be specific about singular (single item) and plural (list of items) in cement api

module_utils/ansible_nailgun_cement.py, modules/foreman_global_parameter.py
This is based upon https://github.com/theforeman/foreman-ansible-modules/pull/25
=> Port global parameters to cement

test/demo/global_parameter.yml, test/demo/ptable.yml
=> add demo playbooks for global parameter and ptable

module_utils/ansible_nailgun_cement.py, modules/foreman_global_parameter.py, modules/foreman_provisioning_template.py, modules/foreman_ptable.py
After disabling the announcement, it was not too hard to actually implement the 'check_mode'.
=> Check mode in cement

modules/katello_upload.py
this requires https://github.com/SatelliteQE/nailgun/pull/436
=> katello_upload: add support for content_uploads API

modules/foreman_organization.py, test/data/organization.json, test/demo/organizations.yml
As requested in:
https://github.com/theforeman/foreman-ansible-modules/issues/37
=> port foreman_organization to cement

README.md, module_utils/ansible_nailgun_cement.py, modules/foreman_compute_resource.py, test/data/compute-resource.json, test/demo/compute-resource.yml
Based on #25 
Adds a module for compute resources
Nailgun PR for ComputeResource types found in cement will be created
=> Add compute resource module

module_utils/ansible_nailgun_cement.py
I think, it's kind of obvious...
=> Use yaml.safe_load instead of yaml.load

module_utils/ansible_nailgun_cement.py, module_utils/foreman_helper.py, modules/foreman_compute_resource.py, modules/foreman_global_parameter.py, modules/foreman_organization.py, modules/foreman_provisioning_template.py, modules/foreman_ptable.py, modules/katello_activation_key.py, modules/katello_content_view.py, modules/katello_lifecycle_environment.py, modules/katello_manifest.py, modules/katello_product.py, modules/katello_publish.py, modules/katello_repository.py, modules/katello_repository_set.py, modules/katello_sync.py, modules/katello_sync_plan.py, modules/katello_upload.py
I am collecting small fixups on this branch i stumble across.
I do not want to make a Pull request for all of them, but eventually squash them thematically in no more than a handfull commits.
It is in no way meant to be a review covering the full codebase (to lazy).
Feel free to add more of those unrelated commits, or to cherry-pick things you think are urgent.
Effects:
https://github.com/theforeman/foreman-ansible-modules/issues/32
https://github.com/theforeman/foreman-ansible-modules/issues/29
fixes #47
=> RFC: Collection of small fixes

modules/katello_content_view_version_promote.py
=> katello_content_view_version_promote: default to verify_ssl=True

modules/katello_content_view.py, modules/katello_product.py, modules/katello_repository.py, modules/katello_sync_plan.py
Another sore spot on my git-blame-profile. This time i was tricked.
@akofink did you ever test this stuff?
=> Repair checkmode in katello_*

test/demo/compute-resource.yml, test/demo/content-views.yml, test/demo/lifecycle_environment.yml, test/demo/manifests.yml, test/demo/repository-set.yml
I didn't change any of the content; it's all spacing changes except content-views.yml and repository-set.yml
=> Fix (mostly) syntax issues in demo files

module_utils/ansible_nailgun_cement.py, modules/foreman_realm.py, test/data/realm.json, test/demo/realm.yml
foreman-ansible-modules:
- New Realm module to support create and delete of realms in Foreman/Satellite 6 modules/foreman_realm.py
- Added realm.json file to support testing using Ansible hacking: ./.tmp/ansible/hacking/test-module -m modules/foreman_realm.py  -a @test/data/realm.json" test/data/realm.json
- Added realm.yml as example on how to create/delete a realm" test/demo/realm.yml
- Added choices to realm_type: "Red Hat Identity Management", "Active Directory", "FreeIPA"
Here is a test for deleting on a REALM:
```
TEST 1:
[claudiol@fedora26 lmco-cos]$ ansible-playbook -i ./inventory test-realm-module.yml
PLAY [satellite.redhat.local] **************************************************
TASK [Gathering Facts] *********************************************************
ok: …
```
=> Foreman Realm create/delete 

module_utils/ansible_nailgun_cement.py, modules/foreman_compute_resource.py, modules/foreman_global_parameter.py, modules/foreman_provisioning_template.py, modules/foreman_ptable.py
fixes: https://github.com/theforeman/foreman-ansible-modules/issues/30
=> Rename cement states

module_utils/ansible_nailgun_cement.py, modules/foreman_compute_profile.py, test/data/compute-profile.json, test/demo/compute_profile.yml
Based on #25
Adds a module for compute profiles
=> Add compute profile module

README.md, module_utils/ansible_nailgun_cement.py, modules/foreman_operating_system.py, modules/foreman_os_default_template.py, test/data/operating-system.json, test/data/os-default-template.json, test/demo/operating_system.yml, test/demo/os_default_template.yml
This adds yet another module. Hurray!
This time for Operating systems.
=> Foreman operatingsystem

modules/katello_product.py, test/data/product.json, test/demo/product.yml
* add test data
affects: #37 
Introduces the ability to delete Products.
=> Port katello_product to cement

modules/katello_repository.py, test/demo/repository.yml
Sadly nailgun allows this write-only...
=> add download_policy to katello_repository

modules/foreman_operating_system.py, modules/foreman_provisioning_template.py
this commit is to fix some "very bad" typos :D
#opensourcefriday
=> important typo-fixes ;)

module_utils/ansible_nailgun_cement.py, modules/foreman_operating_system.py, modules/foreman_os_default_template.py, modules/foreman_provisioning_template.py
Searching for operating systems seems more complicated than other entities...
=> Search Operatingsystems by title

modules/katello_sync.py
Note, this doesn't changed the current default
https://github.com/SatelliteQE/nailgun/blob/master/nailgun/entities.py#L4639
https://github.com/SatelliteQE/nailgun/blob/master/nailgun/entities.py#L5163
=> allow for aysnc katello_sync

test/test_crud.py, test/test_playbooks/compute_profile.yml, test/test_playbooks/fixtures/compute_profile-1.yml, test/test_playbooks/fixtures/compute_profile-3.yml, test/test_playbooks/fixtures/global_parameter-1.yml, test/test_playbooks/fixtures/global_parameter-3.yml, test/test_playbooks/fixtures/global_parameter-5.yml, test/test_playbooks/fixtures/global_parameter-7.yml, test/test_playbooks/fixtures/operating_system-1.yml, test/test_playbooks/fixtures/operating_system-3.yml, test/test_playbooks/fixtures/operating_system-5.yml, test/test_playbooks/fixtures/operating_system-7.yml, test/test_playbooks/global_parameter.yml, test/test_playbooks/operating_system.yml, test/test_playbooks/tasks/global_parameter.yml
affects: #77 
This is based on #76 which should be merged first.
=> Test playbooks

modules/foreman_provisioning_template.py, modules/foreman_ptable.py
The examples show how to import local files via lookup.
=> Add examples to ptable and provisioning template

modules/katello_product.py, test/test_playbooks/tasks/product.yml
Brings in the changes from #79
=> Cleanup katello_product state in doc and test

module_utils/ansible_nailgun_cement.py, modules/katello_repository.py, test/test_crud.py, test/test_playbooks/fixtures/repository-1.yml, test/test_playbooks/fixtures/repository-3.yml, test/test_playbooks/fixtures/repository-5.yml, test/test_playbooks/fixtures/repository-7.yml, test/test_playbooks/fixtures/repository-9.yml, test/test_playbooks/repository.yml, test/test_playbooks/tasks/repository.yml
Includes the fixed tests from mdellweg (but I did a lazy pull so lost the commit)
Pulls changes from #79
=> Refactory katello_repository to utilize cement

test/test_playbooks/fixtures/repository-1.yml, test/test_playbooks/fixtures/repository-3.yml, test/test_playbooks/fixtures/repository-5.yml, test/test_playbooks/fixtures/repository-7.yml, test/test_playbooks/fixtures/repository-9.yml
No sure, why they were needed, but atm master fails the tests...
=> Rerecord Repository fixtures

test/test_crud.py, test/test_playbooks/fixtures/lifecycle_environment-1.yml, test/test_playbooks/fixtures/lifecycle_environment-11.yml, test/test_playbooks/fixtures/lifecycle_environment-13.yml, test/test_playbooks/fixtures/lifecycle_environment-3.yml, test/test_playbooks/fixtures/lifecycle_environment-5.yml, test/test_playbooks/fixtures/lifecycle_environment-7.yml, test/test_playbooks/fixtures/lifecycle_environment-9.yml, test/test_playbooks/lifecycle_environment.yml, test/test_playbooks/tasks/lifecycle_environment.yml
=> Add test for lifecycle_environment

test/test_playbooks/fixtures/operating_system-1.yml, test/test_playbooks/fixtures/operating_system-3.yml, test/test_playbooks/fixtures/operating_system-5.yml, test/test_playbooks/fixtures/operating_system-7.yml, test/test_playbooks/location.yml, test/test_playbooks/operating_system.yml, test/test_playbooks/organization.yml, test/test_playbooks/tasks/operating_system.yml
And fix typos in tests.
just like #99
=> Restructure operating system tests

test/test_playbooks/compute_profile.yml, test/test_playbooks/fixtures/compute_profile-3.yml, test/test_playbooks/fixtures/compute_profile-5.yml, test/test_playbooks/fixtures/compute_profile-7.yml, test/test_playbooks/tasks/compute_profile.yml
I was quite confident with the yaml subclassing method, but as it was inconsistent with the other tests, and we have already seen people being confused, i adapted the 'global scheme'.
Also i inflated the test a little. ;)
=> Restructure and improve test for compute_profile

module_utils/foreman_helper.py, test/test_crud.py, test/test_playbooks/fixtures/provisioning_template-1.yml, test/test_playbooks/fixtures/provisioning_template-3.yml, test/test_playbooks/fixtures/provisioning_template-5.yml, test/test_playbooks/fixtures/provisioning_template-7.yml, test/test_playbooks/fixtures/provisioning_template-9.yml, test/test_playbooks/fixtures/ptable-1.yml, test/test_playbooks/fixtures/ptable-3.yml, test/test_playbooks/fixtures/ptable-5.yml, test/test_playbooks/fixtures/ptable-7.yml, test/test_playbooks/fixtures/ptable-9.yml, test/test_playbooks/provisioning_template.yml, test/test_playbooks/ptable.yml, test/test_playbooks/tasks/provisioning_template.yml, test/test_playbooks/tasks/ptable.yml
Based on #90.
This test does not pass when run against current foreman/katello nightly due to a bug (Redmine: 22303).
Thanks to @akofink helping to figure this out.
=> Test provisioning template

modules/foreman_global_parameter.py, modules/foreman_location.py, modules/foreman_operating_system.py, modules/foreman_organization.py, modules/foreman_os_default_template.py, modules/foreman_provisioning_template.py, modules/foreman_ptable.py, modules/foreman_realm.py, modules/katello_lifecycle_environment.py, modules/katello_manifest.py, modules/katello_product.py, modules/katello_repository.py
=> Set the default for 'state' to 'present'

modules/foreman_location.py, test/test_playbooks/fixtures/location-1.yml, test/test_playbooks/fixtures/location-5.yml, test/test_playbooks/fixtures/location-7.yml, test/test_playbooks/fixtures/location-9.yml, test/test_playbooks/location.yml, test/test_playbooks/tasks/location.yml
=> Add Option to nest locations

module_utils/ansible_nailgun_cement.py, modules/foreman_global_parameter.py, modules/foreman_provisioning_template.py, modules/foreman_ptable.py, modules/katello_product.py, modules/katello_repository.py
* Remove the shadowing entity for global parameter, as the functionality has been added to nailgun.
* Import entities directly from nailgun if they are not modified in cement.
=> Remove shadow entities

test/test_crud.py, test/test_playbooks/fixtures/os_default_template-1.yml, test/test_playbooks/fixtures/os_default_template-3.yml, test/test_playbooks/fixtures/os_default_template-5.yml, test/test_playbooks/fixtures/os_default_template-7.yml, test/test_playbooks/os_default_template.yml, test/test_playbooks/tasks/os_default_template.yml
Despite the label text, this depends on *two* other PRs: #91 #101
=>  Add tests for os_default_template 

modules/foreman_operating_system.py, test/test_playbooks/fixtures/operating_system-1.yml, test/test_playbooks/fixtures/operating_system-3.yml, test/test_playbooks/fixtures/operating_system-5.yml, test/test_playbooks/fixtures/operating_system-7.yml, test/test_playbooks/tasks/operating_system.yml
=> Add release_name to operatingsystem

module_utils/foreman_helper.py, modules/foreman_compute_profile.py, modules/foreman_compute_resource.py, modules/foreman_domain.py, modules/foreman_global_parameter.py, modules/foreman_location.py, modules/foreman_operating_system.py, modules/foreman_organization.py, modules/foreman_os_default_template.py, modules/foreman_provisioning_template.py, modules/foreman_ptable.py, modules/foreman_realm.py, modules/foreman_setting.py, modules/foreman_setting_facts.py, modules/katello_activation_key.py, modules/katello_content_view.py, modules/katello_content_view_publish.py, modules/katello_content_view_version_promote.py, modules/katello_lifecycle_environment.py, modules/katello_manifest.py, modules/katello_product.py, modules/katello_repository.py, modules/katello_repository_set.py, modules/katello_sync.py, modules/katello_sync_plan.py, modules/katello_upload.py
Print what actually couldn't be imported instead of just "Missing required nailgun module (check docs or install with: pip install nailgun)".
=> Print import errors

README.md, module_utils/ansible_nailgun_cement.py, modules/foreman_job_template.py, test/test_crud.py, test/test_playbooks/delete_file.erb, test/test_playbooks/fixtures/job_template-1.yml, test/test_playbooks/fixtures/job_template-11.yml, test/test_playbooks/fixtures/job_template-13.yml, test/test_playbooks/fixtures/job_template-15.yml, test/test_playbooks/fixtures/job_template-17.yml, test/test_playbooks/fixtures/job_template-3.yml, test/test_playbooks/fixtures/job_template-5.yml, test/test_playbooks/fixtures/job_template-7.yml, test/test_playbooks/fixtures/job_template-9.yml, test/test_playbooks/job_template.yml, test/test_playbooks/tasks/job_template.yml, test/test_playbooks/tasks/job_template_from_file.yml
Add JobTemplate and TemplateInput class to cement
Manage template inputs
Add test playbooks
Todo:
=> Add job templates module

test/test_crud.py, test/test_playbooks/content_view.yml, test/test_playbooks/fixtures/content_view-1.yml, test/test_playbooks/fixtures/content_view-3.yml, test/test_playbooks/tasks/content_view.yml, test/vcr_python_wrapper.py
in preparation for a content_view_filter module
=> Added Content vew tests

test/test_crud.py, test/test_playbooks/fixtures/repository_sync-1.yml, test/test_playbooks/fixtures/repository_sync-3.yml, test/test_playbooks/repository_sync.yml, test/test_playbooks/tasks/repository_sync.yml
in preparation for a content_view_filter module
=> add katello_sync tests

module_utils/ansible_nailgun_cement.py, modules/katello_content_view.py, test/test_playbooks/content_view.yml, test/test_playbooks/fixtures/content_view-3.yml, test/test_playbooks/fixtures/content_view-5.yml, test/test_playbooks/fixtures/content_view-7.yml, test/test_playbooks/tasks/content_view.yml
Includes a refactor so `katello_content_view` is more reliant on cement
=> Add content view state var

modules/katello_repository.py, test/test_playbooks/fixtures/repository-1.yml, test/test_playbooks/fixtures/repository-11.yml, test/test_playbooks/fixtures/repository-13.yml, test/test_playbooks/fixtures/repository-15.yml, test/test_playbooks/fixtures/repository-3.yml, test/test_playbooks/fixtures/repository-5.yml, test/test_playbooks/fixtures/repository-9.yml, test/test_playbooks/repository.yml, test/test_playbooks/tasks/repository.yml
Also required for the newly incoming content_view_filter module tests.
Apologies for the onslaught of PRs :rocket:
=> add docker support to katello_repository

.travis.yml, Makefile, modules/foreman_job_template.py, test/extras/sanity.yml
This adds tests from Ansible core `ansible-test sanity --test ansible-doc --test compile`
It also fixes an issue with `modules/foreman_job_template.py` so these new amazing tests pass.
=> add sanity tests

modules/katello_repository.py, test/test_playbooks/fixtures/repository-1.yml, test/test_playbooks/fixtures/repository-11.yml, test/test_playbooks/fixtures/repository-13.yml, test/test_playbooks/fixtures/repository-15.yml, test/test_playbooks/fixtures/repository-3.yml, test/test_playbooks/fixtures/repository-5.yml, test/test_playbooks/fixtures/repository-7.yml, test/test_playbooks/fixtures/repository-9.yml, test/test_playbooks/tasks/repository.yml
fixes https://github.com/theforeman/foreman-ansible-modules/issues/151
=> Add label to repositories

requirements-dev.txt
Without this tests are using the released version of nailgun on pypi
=> make tests use nailgun from source

modules/katello_activation_key.py, test/test_playbooks/activation_key.yml, test/test_playbooks/fixtures/activation_key-1.yml, test/test_playbooks/fixtures/activation_key-11.yml, test/test_playbooks/fixtures/activation_key-13.yml, test/test_playbooks/fixtures/activation_key-15.yml, test/test_playbooks/fixtures/activation_key-17.yml, test/test_playbooks/fixtures/activation_key-19.yml, test/test_playbooks/fixtures/activation_key-3.yml, test/test_playbooks/fixtures/activation_key-5.yml, test/test_playbooks/fixtures/activation_key-7.yml, test/test_playbooks/fixtures/activation_key-9.yml, test/test_playbooks/tasks/activation_key.yml
=> implement content overrides for k_activation_key

module_utils/ansible_nailgun_cement.py, modules/foreman_job_template.py
'template_input_list' should not be undefined.
=> Fix Job Template module

modules/katello_upload.py
This causes issues with other content types that are not rpm
=> Only run rpm query for yum repo

modules/redhat_manifest.py, requirements-dev.txt, test/ansible_fail.py
nobody wants to support Python 2.4 :)
=> drop simplejson

modules/foreman_provisioning_template.py, test/test_playbooks/fixtures/provisioning_template-0.yml, test/test_playbooks/fixtures/provisioning_template-1.yml, test/test_playbooks/fixtures/provisioning_template-2.yml, test/test_playbooks/fixtures/provisioning_template-4.yml, test/test_playbooks/fixtures/provisioning_template-5.yml, test/test_playbooks/fixtures/provisioning_template-6.yml, test/test_playbooks/fixtures/provisioning_template-7.yml, test/test_playbooks/fixtures/provisioning_template-8.yml, test/test_playbooks/fixtures/provisioning_template-9.yml, test/test_playbooks/provisioning_template.yml, test/test_playbooks/tasks/provisioning_template.yml
Remove the default value for the locked state otherwise the locked state
will be set to "false" in case the "locked" option is not given. Set the
locked state to true/false if you want to change the locked state. In
case of a new template, the locked state is set to false automatically
as this is the default on the foreman side.
=> Remove default value for locked state

modules/foreman_ptable.py, test/test_playbooks/fixtures/ptable-0.yml, test/test_playbooks/fixtures/ptable-1.yml, test/test_playbooks/fixtures/ptable-3.yml, test/test_playbooks/fixtures/ptable-4.yml, test/test_playbooks/fixtures/ptable-5.yml, test/test_playbooks/fixtures/ptable-6.yml, test/test_playbooks/fixtures/ptable-7.yml, test/test_playbooks/fixtures/ptable-8.yml, test/test_playbooks/fixtures/ptable-9.yml, test/test_playbooks/ptable.yml, test/test_playbooks/tasks/ptable.yml
Requires:
- https://github.com/theforeman/foreman/pull/5741
- https://github.com/SatelliteQE/nailgun/pull/503
=> Adding locked state to ptable

module_utils/ansible_nailgun_cement.py, modules/foreman_search_facts.py, test/test_crud.py, test/test_playbooks/fixtures/search_facts-0.yml, test/test_playbooks/fixtures/search_facts-1.yml, test/test_playbooks/search_facts.yml, test/test_playbooks/tasks/search_facts.yml
This module allows searching any Entity as long as it has `EntitySearchMixin` within Nailgun
=> Add foreman_search_facts module

README.md, module_utils/ansible_nailgun_cement.py, modules/katello_upload.py, test/test_playbooks/data/file_repo_test.txt, test/test_playbooks/fixtures/upload-2.yml, test/test_playbooks/fixtures/upload-3.yml, test/test_playbooks/upload.yml
Requires https://github.com/SatelliteQE/nailgun/pull/562
=> Make katello_upload idempotent with Files

modules/katello_content_view_version.py
To test:
```yaml
- name: Promote cv1 Library to the Devel and Test environments
katello_content_view_version:
username: "{{ foreman_username }}"
password: "{{ foreman_password }}"
server_url: "{{ foreman_server_url }}"
verify_ssl: "{{ foreman_verify_ssl }}"
content_view: cv1
organization: Default Organization
force: true
current_lifecycle_environment: Library
lifecycle_environments:
- Devel
- Test
```
=> Use singular Nailgun resource CVV.environement

module_utils/ansible_nailgun_cement.py, modules/foreman_setting.py, test/test_playbooks/fixtures/setting-0.yml, test/test_playbooks/fixtures/setting-1.yml, test/test_playbooks/fixtures/setting-2.yml, test/test_playbooks/fixtures/setting-4.yml, test/test_playbooks/fixtures/setting-5.yml, test/test_playbooks/fixtures/setting-6.yml, test/test_playbooks/fixtures/setting-7.yml, test/test_playbooks/fixtures/setting-8.yml, test/test_playbooks/setting.yml, test/test_playbooks/tasks/setting.yml
Admittedly I'm not 100% on board with the way I have fixed this, but I think its the best way :/
I'd welcome some other suggestions
=> foreman_setting now supports array and int values

modules/katello_sync.py
Since this is somewhat complicated, It may be worth having an example. I suspect this may be a common task?
=> Add example to Sync all repositories

test/test_playbooks/fixtures/repository-0.yml, test/test_playbooks/fixtures/repository-1.yml, test/test_playbooks/fixtures/repository-10.yml, test/test_playbooks/fixtures/repository-11.yml, test/test_playbooks/fixtures/repository-2.yml, test/test_playbooks/fixtures/repository-3.yml, test/test_playbooks/fixtures/repository-4.yml, test/test_playbooks/fixtures/repository-5.yml, test/test_playbooks/fixtures/repository-6.yml, test/test_playbooks/fixtures/repository-7.yml, test/test_playbooks/fixtures/repository-8.yml, test/test_playbooks/fixtures/repository-9.yml
9029a698a012ce5dc5dad11a0c55c420eafc42e9
=> Fix repository tests because of nailgun commit 9029a698

module_utils/ansible_nailgun_cement.py, modules/katello_repository_set.py, test/test_crud.py, test/test_playbooks/fixtures/repository_set-1.yml, test/test_playbooks/fixtures/repository_set-2.yml, test/test_playbooks/fixtures/repository_set-3.yml, test/test_playbooks/fixtures/repository_set-4.yml, test/test_playbooks/fixtures/repository_set-5.yml, test/test_playbooks/repository_set.yml, test/test_playbooks/tasks/repository_set.yml
Requires ~~SatelliteQE/nailgun#574~~
=> Repository Sets: make name & product optional inplace of label

module_utils/ansible_nailgun_cement.py, modules/katello_content_view.py, modules/katello_content_view_version.py, test/test_playbooks/content_view.yml, test/test_playbooks/fixtures/content_view-0.yml, test/test_playbooks/fixtures/content_view-1.yml, test/test_playbooks/fixtures/content_view-10.yml, test/test_playbooks/fixtures/content_view-11.yml, test/test_playbooks/fixtures/content_view-12.yml, test/test_playbooks/fixtures/content_view-13.yml, test/test_playbooks/fixtures/content_view-14.yml, test/test_playbooks/fixtures/content_view-15.yml, test/test_playbooks/fixtures/content_view-4.yml, test/test_playbooks/fixtures/content_view-5.yml, test/test_playbooks/fixtures/content_view-6.yml, test/test_playbooks/fixtures/content_view-7.yml, test/test_playbooks/fixtures/content_view-8.yml, test/test_playbooks/fixtures/content_view-9.yml, test/test_playbooks/tasks/content_view.yml, test/test_playbooks/tasks/content_view_version.yml
Requires:
- ~~https://github.com/SatelliteQE/nailgun/pull/558~~
- ~~https://github.com/theforeman/foreman-ansible-modules/pull/201~~
=> Support Composite content views

modules/foreman_subnet.py
https://github.com/SatelliteQE/nailgun/issues/606 broke our tests, nice that we didnt have to re-record any tapes.
=> renamed subnet param from to from_

module_utils/ansible_nailgun_cement.py
This was added to Nailgun in https://github.com/SatelliteQE/nailgun/commit/47cb8484dfc901a98f2806262cbe1dbcf809475b
=> remove ComputeProfile class

module_utils/foreman_helper.py, modules/foreman_compute_profile.py, modules/foreman_domain.py, modules/foreman_environment.py, modules/foreman_global_parameter.py, modules/foreman_installation_medium.py, modules/foreman_job_template.py, modules/foreman_location.py, modules/foreman_operating_system.py, modules/foreman_organization.py, modules/foreman_os_default_template.py, modules/foreman_provisioning_template.py, modules/foreman_ptable.py, modules/foreman_search_facts.py, modules/foreman_setting.py, modules/foreman_subnet.py, modules/katello_activation_key.py, modules/katello_content_credential.py, modules/katello_content_view.py, modules/katello_content_view_filter.py, modules/katello_lifecycle_environment.py, modules/katello_product.py, modules/katello_repository.py, modules/katello_repository_set.py, modules/katello_sync_plan.py, modules/katello_upload.py
this only touches the domain module, I'd apply the same pattern to all others if y'all like this.
=> move common argument spec entries to a common module base

modules/foreman_search_facts.py, modules/katello_content_view.py, modules/katello_content_view_filter.py
Ansible has documented these at https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html#linking-within-module-documentation
=> use correct link types

module_utils/foreman_helper.py, modules/foreman_compute_profile.py, modules/foreman_domain.py, modules/foreman_environment.py, modules/foreman_global_parameter.py, modules/foreman_installation_medium.py, modules/foreman_job_template.py, modules/foreman_location.py, modules/foreman_operating_system.py, modules/foreman_organization.py, modules/foreman_os_default_template.py, modules/foreman_provisioning_template.py, modules/foreman_ptable.py, modules/foreman_search_facts.py, modules/foreman_setting.py, modules/foreman_subnet.py, modules/katello_activation_key.py, modules/katello_content_credential.py, modules/katello_content_view.py, modules/katello_content_view_filter.py, modules/katello_lifecycle_environment.py, modules/katello_product.py, modules/katello_repository.py, modules/katello_repository_set.py, modules/katello_sync_plan.py, modules/katello_upload.py
as always, this is an example, I intend to adjust that across all (tested) modules
=> streamline the way we connect/ping to the server

module_utils/ansible_nailgun_cement.py, modules/foreman_compute_profile.py, test/test_playbooks/compute_profile.yml, test/test_playbooks/compute_profile_vars.yml, test/test_playbooks/fixtures/compute_profile-0.yml, test/test_playbooks/fixtures/compute_profile-2.yml, test/test_playbooks/fixtures/compute_profile-3.yml, test/test_playbooks/fixtures/compute_profile-4.yml, test/test_playbooks/fixtures/compute_profile-5.yml, test/test_playbooks/fixtures/compute_profile-6.yml, test/test_playbooks/tasks/compute_profile.yml
* Fixes #222
* Add compute attributes support
* Tests improvements
=> Fixes #222 - Add compute_attributes support

README.md
I feel like this would have helped me the first time I read it.
Feel free to disagree/close if you think otherwise.
=> Add some minor clarifications to the README.md file

modules/foreman_operating_system.py
Also fix documentation.
Fixes: #218
=> Add meaningful examples to operating system

modules/katello_repository_set.py
https://github.com/theforeman/foreman-ansible-modules/issues/166
=> Document repository_set label param

module_utils/ansible_nailgun_cement.py, modules/foreman_bookmark.py, test/test_crud.py, test/test_playbooks/bookmark.yml, test/test_playbooks/fixtures/bookmark-0.yml, test/test_playbooks/fixtures/bookmark-1.yml, test/test_playbooks/fixtures/bookmark-2.yml, test/test_playbooks/fixtures/bookmark-3.yml, test/test_playbooks/fixtures/bookmark-4.yml, test/test_playbooks/fixtures/bookmark-5.yml, test/test_playbooks/fixtures/bookmark-6.yml, test/test_playbooks/tasks/bookmark.yml
This is WIP - the module is "done" - however I cannot get the test running yet.
Will keep trying ;)
=> Add Bookmark module

module_utils/ansible_nailgun_cement.py
* JobTemplate
* TemplateInput
* OVirtComputeResource
* VMWareComputeResource
=> Remove local entities

module_utils/ansible_nailgun_cement.py, modules/foreman_host.py, modules/foreman_host_power.py, test/test_crud.py, test/test_playbooks/fixtures/host-0.yml, test/test_playbooks/fixtures/host-1.yml, test/test_playbooks/fixtures/host-2.yml, test/test_playbooks/fixtures/host-3.yml, test/test_playbooks/fixtures/host-4.yml, test/test_playbooks/fixtures/host-5.yml, test/test_playbooks/fixtures/host-6.yml, test/test_playbooks/fixtures/host-7.yml, test/test_playbooks/fixtures/host-8.yml, test/test_playbooks/host.yml, test/test_playbooks/power_host.yml, test/test_playbooks/tasks/host.yml, test/test_playbooks/tasks/host_power.yml
To solve #256
Current state:
15.3.2019
Module can use a preexisting host-group to create a new host
15.3.2019
Can create and delete hosts
=> New host module

module_utils/ansible_nailgun_cement.py, modules/katello_sync_plan.py, test/test_playbooks/fixtures/sync_plan-1.yml, test/test_playbooks/fixtures/sync_plan-2.yml, test/test_playbooks/fixtures/sync_plan-3.yml, test/test_playbooks/fixtures/sync_plan-4.yml, test/test_playbooks/fixtures/sync_plan-5.yml, test/test_playbooks/fixtures/sync_plan-6.yml, test/test_playbooks/sync_plan.yml, test/test_playbooks/tasks/sync_plan.yml
=> Refactor katello_sync_plan to cement

Makefile, modules/katello_activation_key.py, test/test_crud.py, test/test_playbooks/activation_key.yml, test/test_playbooks/fixtures/activation_key-0.yml, test/test_playbooks/fixtures/activation_key-1.yml, test/test_playbooks/fixtures/activation_key-2.yml, test/test_playbooks/fixtures/activation_key-3.yml, test/test_playbooks/fixtures/activation_key-4.yml, test/test_playbooks/fixtures/activation_key-5.yml, test/test_playbooks/fixtures/activation_key-6.yml, test/test_playbooks/fixtures/activation_key-7.yml, test/test_playbooks/fixtures/activation_key-8.yml, test/test_playbooks/fixtures/activation_key-9.yml, test/test_playbooks/tasks/activation_key.yml
=> Repair activation_key test

modules/katello_product.py, test/test_playbooks/fixtures/product-0.yml, test/test_playbooks/fixtures/product-1.yml, test/test_playbooks/fixtures/product-10.yml, test/test_playbooks/fixtures/product-11.yml, test/test_playbooks/fixtures/product-12.yml, test/test_playbooks/fixtures/product-2.yml, test/test_playbooks/fixtures/product-4.yml, test/test_playbooks/fixtures/product-5.yml, test/test_playbooks/fixtures/product-6.yml, test/test_playbooks/fixtures/product-7.yml, test/test_playbooks/fixtures/product-9.yml, test/test_playbooks/product.yml, test/test_playbooks/tasks/product.yml
Add ability to set sync_plan on product.
=> Add sync plan support for product.

requirements-dev.txt, test/test_crud.py
this fixes ansible 2.8 problems too
=> migrate to ansible-runner

test/test_crud.py
ansible_runner does not like unicode
=> strip unicode from the env when running on py2

module_utils/foreman_helper.py, modules/foreman_search_facts.py, test/test_playbooks/fixtures/search_facts-0.yml, test/test_playbooks/fixtures/search_facts-1.yml, test/test_playbooks/fixtures/search_facts-2.yml, test/test_playbooks/search_facts.yml
this allows the user to list all available resources on the server
=> add back usefull failure mode to search_facts

modules/foreman_organization.py, test/test_playbooks/fixtures/organization-0.yml, test/test_playbooks/fixtures/organization-1.yml, test/test_playbooks/fixtures/organization-3.yml, test/test_playbooks/organization.yml, test/test_playbooks/tasks/organization.yml
Make it possible to set (and change) the description of an
organization using the foreman_organization module.
=> Add description to foreman_organization

modules/foreman_role.py, test/test_playbooks/domain_vars.yml, test/test_playbooks/fixtures/domain-0.yml, test/test_playbooks/fixtures/domain-1.yml, test/test_playbooks/fixtures/domain-2.yml, test/test_playbooks/fixtures/domain-3.yml, test/test_playbooks/fixtures/domain-4.yml, test/test_playbooks/server_vars.yml.example, test/vcr_python_wrapper.py
* Rerecord domain
* Ignore smart_proxy name in domain test playback
* Also move domain_dns_proxy variable to server_vars.yml as it is volatile.
=> Repare tests

plugins/module_utils/foreman_helper.py, requirements-common.txt, requirements-dev.txt, requirements.txt
we moved the generate params helper there, so no need to carry our copy
=> use apypie 0.0.2

test/test_playbooks/tasks/host.yml, test/test_playbooks/vars/server.yml.example, test/vcr_python_wrapper.py
Edited new matcher to ignore hostgroup for host test.
=> Modify vcr_python_wrapper for host test

plugins/modules/katello_manifest.py
=> Fix spelling

plugins/module_utils/foreman_helper.py, plugins/modules/foreman_architecture.py, plugins/modules/foreman_auth_source_ldap.py, plugins/modules/foreman_bookmark.py, plugins/modules/foreman_compute_attribute.py, plugins/modules/foreman_compute_profile.py, plugins/modules/foreman_compute_resource.py, plugins/modules/foreman_domain.py, plugins/modules/foreman_environment.py, plugins/modules/foreman_global_parameter.py, plugins/modules/foreman_host.py, plugins/modules/foreman_host_power.py, plugins/modules/foreman_hostgroup.py, plugins/modules/foreman_installation_medium.py, plugins/modules/foreman_job_template.py, plugins/modules/foreman_location.py, plugins/modules/foreman_operating_system.py, plugins/modules/foreman_organization.py, plugins/modules/foreman_os_default_template.py, plugins/modules/foreman_provisioning_template.py, plugins/modules/foreman_ptable.py, plugins/modules/foreman_role.py, plugins/modules/foreman_search_facts.py, plugins/modules/foreman_setting.py, plugins/modules/foreman_subnet.py, plugins/modules/foreman_user.py, plugins/modules/katello_content_view_filter.py, plugins/modules/katello_sync.py, plugins/modules/katello_sync_plan.py, plugins/modules/katello_upload.py
=> default to supports_check_mode=True

Makefile, plugins/module_utils/foreman_helper.py, plugins/modules/foreman_architecture.py, plugins/modules/foreman_auth_source_ldap.py, plugins/modules/foreman_domain.py, plugins/modules/foreman_environment.py, plugins/modules/foreman_location.py, plugins/modules/foreman_role.py, plugins/modules/foreman_user.py
Unify the interface and make the default for thin more explicit.
=> Refactor find methods

plugins/modules/foreman_subnet.py, tests/test_playbooks/fixtures/subnet-0.yml, tests/test_playbooks/fixtures/subnet-1.yml, tests/test_playbooks/fixtures/subnet-10.yml, tests/test_playbooks/fixtures/subnet-11.yml, tests/test_playbooks/fixtures/subnet-12.yml, tests/test_playbooks/fixtures/subnet-2.yml, tests/test_playbooks/fixtures/subnet-5.yml, tests/test_playbooks/fixtures/subnet-6.yml, tests/test_playbooks/fixtures/subnet-7.yml, tests/test_playbooks/fixtures/subnet-9.yml, tests/test_playbooks/subnet.yml, tests/test_playbooks/tasks/subnet.yml
=> foreman_subnet: cast netmask to a string after computing it

tests/extras/sanity.yml
it requires to be inside the ansible dir now
=> fix ansible-test execution

README.md, plugins/modules/foreman_config_group.py, tests/fixtures/apidoc/config_group.json, tests/test_crud.py, tests/test_playbooks/config_group.yml, tests/test_playbooks/fixtures/config_group-0.yml, tests/test_playbooks/fixtures/config_group-1.yml, tests/test_playbooks/fixtures/config_group-2.yml, tests/test_playbooks/fixtures/config_group-3.yml, tests/test_playbooks/fixtures/config_group-4.yml, tests/test_playbooks/fixtures/config_group-5.yml, tests/test_playbooks/fixtures/config_group-6.yml, tests/test_playbooks/fixtures/config_group-7.yml, tests/test_playbooks/tasks/config_group.yml
Add config groups support.
Needed by #366 to add config_groups tests on hostgroups.
=> Add config_groups support

plugins/modules/foreman_host.py
Tested on RH Satellite 6.5 only.
=> FQDN is formed incorrectly. Fixes #351

plugins/modules/foreman_realm.py, tests/fixtures/apidoc/realm.json, tests/test_crud.py, tests/test_playbooks/fixtures/realm-0.yml, tests/test_playbooks/fixtures/realm-1.yml, tests/test_playbooks/fixtures/realm-2.yml, tests/test_playbooks/realm.yml, tests/test_playbooks/tasks/realm.yml
Finally managed to get this running.
And it shows, that realm is _not_ idempotent.
=> Test realm

plugins/module_utils/foreman_helper.py
The module.params are used by Ansible at least in debug output, so they
should not be modified.
=> Copy the params received by Ansible

plugins/modules/foreman_compute_attribute.py, plugins/modules/foreman_hostgroup.py, requirements.txt
this has various fixes we rely on
also don't specify an apypie version in the modules
=> require apypie 0.0.4

plugins/modules/katello_lifecycle_environment.py, tests/test_playbooks/fixtures/lifecycle_environment-0.yml, tests/test_playbooks/fixtures/lifecycle_environment-1.yml, tests/test_playbooks/fixtures/lifecycle_environment-2.yml, tests/test_playbooks/fixtures/lifecycle_environment-3.yml, tests/test_playbooks/fixtures/lifecycle_environment-4.yml, tests/test_playbooks/fixtures/lifecycle_environment-5.yml, tests/test_playbooks/fixtures/lifecycle_environment-6.yml, tests/test_playbooks/tasks/lifecycle_environment.yml
* Port katello_lifecycle_environment to apypie.
* Some changes global to katello to automaticaly scope entity to organization.
See #274.
=> Port katello_lifecycle_environment to apypie

.gitignore, docs/_templates/plugin.rst.j2
This is a hand picked list of improvements from ansibles plugin.rst.j2.
=> Reimport plugin template for docs

plugins/modules/katello_activation_key.py, tests/test_playbooks/activation_key.yml, tests/test_playbooks/fixtures/activation_key-0.yml, tests/test_playbooks/fixtures/activation_key-1.yml, tests/test_playbooks/fixtures/activation_key-11.yml, tests/test_playbooks/fixtures/activation_key-12.yml, tests/test_playbooks/fixtures/activation_key-13.yml, tests/test_playbooks/fixtures/activation_key-14.yml, tests/test_playbooks/fixtures/activation_key-15.yml, tests/test_playbooks/fixtures/activation_key-16.yml, tests/test_playbooks/fixtures/activation_key-17.yml, tests/test_playbooks/fixtures/activation_key-18.yml, tests/test_playbooks/fixtures/activation_key-19.yml, tests/test_playbooks/fixtures/activation_key-2.yml, tests/test_playbooks/fixtures/activation_key-3.yml, tests/test_playbooks/fixtures/activation_key-4.yml, tests/test_playbooks/fixtures/activation_key-5.yml, tests/test_playbooks/fixtures/activation_key-8.yml, tests/test_playbooks/fixtures/activation_key-9.yml
as written in #419, creating an AK with `auto_attach=false` does not work properly, it needs an `update` for the setting to work.
=> katello_activation_key: idempotent auto_attach

Makefile
this also includes doc_fragments, not only modules and module_utils
=> run pylint on the whole plugins directory

plugins/module_utils/foreman_helper.py
=> patch apidoc to include rex proxy ids for subnets

.travis.yml, Makefile, galaxy.yml, requirements-common.txt, requirements-dev.txt, requirements.txt
this commit ensures that the built collection contains
1. only files we need (no .github etc)
2. no nailgun-based modules
3. imports that work inside a collection
=> make "make dist" generate a working, clean collection

plugins/modules/foreman_compute_attribute.py
Add compute_profile and compute_resource in examples.
=> Compute attribute doc

plugins/modules/katello_activation_key.py
there are no tests for that because they would require working RHEL
subscriptions and synced RHEL content available
=> k_activation_key: add release_version and support_level params

plugins/modules/foreman_host_power.py, tests/test_playbooks/fixtures/host_power-1.yml, tests/test_playbooks/fixtures/host_power-2.yml, tests/test_playbooks/fixtures/host_power-3.yml, tests/test_playbooks/fixtures/host_power-4.yml, tests/test_playbooks/fixtures/host_power-5.yml, tests/test_playbooks/fixtures/host_power-6.yml, tests/test_playbooks/fixtures/host_power-7.yml, tests/test_playbooks/host_power.yml, tests/test_playbooks/tasks/host_power.yml
* Port host_power to apypie
* Add some state aliases supported by foreman
* Make hostname an alias of name
=> Port host_power to apypie

plugins/module_utils/foreman_helper.py
apypie doesn't fail on this (anymore)
=> don't patch subscription upload api

plugins/modules/foreman_provisioning_template.py
=> fix erb template in provisioning template example

Makefile, ansible.cfg, requirements-dev.txt, tests/extras/sanity.yml
=> use installed ansible-test

plugins/modules/foreman_auth_source_ldap.py
=> don't set version_added

plugins/modules/foreman_bookmark.py, plugins/modules/foreman_compute_resource.py, plugins/modules/foreman_global_parameter.py, plugins/modules/foreman_job_template.py, plugins/modules/foreman_operatingsystem.py, plugins/modules/foreman_os_default_template.py, plugins/modules/foreman_provisioning_template.py, plugins/modules/foreman_ptable.py, plugins/modules/katello_activation_key.py, plugins/modules/katello_content_view.py, plugins/modules/katello_product.py, plugins/modules/katello_repository.py
=> document present_with_defaults

galaxy.yml
@evgeni this adds the orcharhino tag to galaxy.yml as requested ;-)
=> add orcharhino tag to galaxy.yml

galaxy.yml
also make license a list as documented in [1]
[1] https://docs.ansible.com/ansible/devel/dev_guide/collections_galaxy_meta.html#collections-galaxy-meta
=> add description and homepage to the galaxy metadata

plugins/module_utils/foreman_helper.py
=> drop ForemanBaseAnsibleModule

plugins/module_utils/foreman_helper.py
before:
```
fixtures | FAILED! => {
"changed": false, 
"msg": "Error while performing create on hosts: 422 Client Error: Unprocessable Entity for url: https://foreman.example.com/api/hosts"
}
```
after:
```
fixtures | FAILED! => {
"changed": false, 
"error": {
"errors": {
"interfaces.name": [
"hostname can contain only lowercase letters, numbers, dashes and dots according to RFC921, RFC952 and RFC1123"
], 
"name": [
"hostname can contain only lowercase letters, numbers, dashes and dots according to RFC921, RFC952 and RFC1123"
]
}, 
"full_messages": [
"Name hostname can contain only lowercase letters, numbers, dashes and dots according to RFC921, RFC952 and RFC1123", 
"Name hostname can contain only lowercase letters, numbers, dashes and dots according to RFC921, RFC952 and RFC1123"
], …
```
=> pass on errors from foreman

plugins/modules/katello_upload.py, requirements-dev.txt
=> use rpm's Python bindings to get details of an RPM

plugins/module_utils/foreman_helper.py
This way we can be sure to always patch the current version of the api.
=> Ping early and always

plugins/modules/katello_content_view_version.py, tests/test_playbooks/content_view_version.yml, tests/test_playbooks/fixtures/content_view_version-0.yml, tests/test_playbooks/fixtures/content_view_version-1.yml, tests/test_playbooks/fixtures/content_view_version-2.yml, tests/test_playbooks/fixtures/content_view_version-3.yml, tests/test_playbooks/fixtures/content_view_version-4.yml, tests/test_playbooks/fixtures/content_view_version-5.yml, tests/test_playbooks/fixtures/content_view_version-6.yml, tests/test_playbooks/fixtures/content_view_version-7.yml, tests/test_playbooks/fixtures/content_view_version-8.yml, tests/test_playbooks/fixtures/content_view_version-9.yml, tests/test_playbooks/tasks/content_view_version.yml
=> Add option 'description' to katello_content_view_version

plugins/modules/foreman_usergroup.py, tests/conftest.py, tests/fixtures/apidoc/usergroup.json, tests/sanity/ignore-2.10.txt, tests/test_playbooks/fixtures/usergroup-0.yml, tests/test_playbooks/fixtures/usergroup-1.yml, tests/test_playbooks/fixtures/usergroup-10.yml, tests/test_playbooks/fixtures/usergroup-11.yml, tests/test_playbooks/fixtures/usergroup-12.yml, tests/test_playbooks/fixtures/usergroup-2.yml, tests/test_playbooks/fixtures/usergroup-3.yml, tests/test_playbooks/fixtures/usergroup-4.yml, tests/test_playbooks/fixtures/usergroup-5.yml, tests/test_playbooks/fixtures/usergroup-6.yml, tests/test_playbooks/fixtures/usergroup-7.yml, tests/test_playbooks/fixtures/usergroup-8.yml, tests/test_playbooks/fixtures/usergroup-9.yml, tests/test_playbooks/tasks/usergroup.yml, tests/test_playbooks/usergroup.yml, tests/test_playbooks/vars/usergroup.yml
Fixes some part of #481 (Don't cover external user groups)
=> Add foreman_usergroup module

plugins/modules/foreman_role.py, tests/test_playbooks/fixtures/role-0.yml, tests/test_playbooks/fixtures/role-1.yml, tests/test_playbooks/fixtures/role-2.yml, tests/test_playbooks/fixtures/role-3.yml, tests/test_playbooks/fixtures/role-4.yml, tests/test_playbooks/fixtures/role-5.yml, tests/test_playbooks/fixtures/role-7.yml, tests/test_playbooks/role.yml
@evgeni one test case I shouldn't have removed is creation of new role together with filters.. now it's fixed.
=> Bugfix: Creation of new roles with filters in one go

plugins/modules/katello_sync_plan.py, tests/test_playbooks/fixtures/sync_plan-0.yml, tests/test_playbooks/fixtures/sync_plan-1.yml, tests/test_playbooks/fixtures/sync_plan-2.yml, tests/test_playbooks/fixtures/sync_plan-3.yml, tests/test_playbooks/fixtures/sync_plan-5.yml, tests/test_playbooks/fixtures/sync_plan-6.yml, tests/test_playbooks/fixtures/sync_plan-7.yml, tests/test_playbooks/fixtures/sync_plan-8.yml, tests/test_playbooks/sync_plan.yml
Add present_with_defaults to sync plan to be able to avoid 'change loops' if we want to manage `sync plan <-> products` association in products and not sync plans.
=> Add present_with_defaults to sync plans

plugins/module_utils/foreman_helper.py, plugins/modules/katello_activation_key.py
resolves #165 - k_activation_key can't add subscriptions that exist multiple times
=> add subs to activation key by pool_id

plugins/module_utils/foreman_helper.py
=> handle Katello-style errors in fail_from_exception

plugins/module_utils/foreman_helper.py
Fixes: #530
Includes #544 for the tests :)
=> store "before" state in ensure entity, not in find

plugins/modules/foreman_search_facts.py
=> search_facts: allow scoping by org directly

plugins/modules/katello_content_view_filter.py, tests/test_playbooks/content_view_filter.yml, tests/test_playbooks/fixtures/content_view_filter-0.yml, tests/test_playbooks/fixtures/content_view_filter-1.yml, tests/test_playbooks/fixtures/content_view_filter-10.yml, tests/test_playbooks/fixtures/content_view_filter-11.yml, tests/test_playbooks/fixtures/content_view_filter-12.yml, tests/test_playbooks/fixtures/content_view_filter-13.yml, tests/test_playbooks/fixtures/content_view_filter-14.yml, tests/test_playbooks/fixtures/content_view_filter-15.yml, tests/test_playbooks/fixtures/content_view_filter-16.yml, tests/test_playbooks/fixtures/content_view_filter-17.yml, tests/test_playbooks/fixtures/content_view_filter-18.yml, tests/test_playbooks/fixtures/content_view_filter-19.yml, tests/test_playbooks/fixtures/content_view_filter-2.yml, tests/test_playbooks/fixtures/content_view_filter-20.yml, tests/test_playbooks/fixtures/content_view_filter-21.yml, tests/test_playbooks/fixtures/content_view_filter-22.yml, tests/test_playbooks/fixtures/content_view_filter-24.yml, tests/test_playbooks/fixtures/content_view_filter-25.yml, tests/test_playbooks/fixtures/content_view_filter-26.yml, tests/test_playbooks/fixtures/content_view_filter-27.yml, tests/test_playbooks/fixtures/content_view_filter-3.yml, tests/test_playbooks/fixtures/content_view_filter-4.yml, tests/test_playbooks/fixtures/content_view_filter-5.yml, tests/test_playbooks/fixtures/content_view_filter-6.yml, tests/test_playbooks/fixtures/content_view_filter-7.yml, tests/test_playbooks/fixtures/content_view_filter-8.yml, tests/test_playbooks/fixtures/content_view_filter-9.yml, tests/test_playbooks/tasks/content_view_filter_package.yml
Adds "Include RPMs without errata" GUI checkbox to this module
Fixes #522
=> add original_packages option to content_view_filter

plugins/modules/foreman_subnet.py
=> add Random DB and EUI-64 IPAM modes

plugins/modules/katello_repository.py, tests/test_playbooks/fixtures/repository-0.yml, tests/test_playbooks/fixtures/repository-1.yml, tests/test_playbooks/fixtures/repository-11.yml, tests/test_playbooks/fixtures/repository-12.yml, tests/test_playbooks/fixtures/repository-13.yml, tests/test_playbooks/fixtures/repository-14.yml, tests/test_playbooks/fixtures/repository-15.yml, tests/test_playbooks/fixtures/repository-16.yml, tests/test_playbooks/fixtures/repository-17.yml, tests/test_playbooks/fixtures/repository-18.yml, tests/test_playbooks/fixtures/repository-19.yml, tests/test_playbooks/fixtures/repository-2.yml, tests/test_playbooks/fixtures/repository-20.yml, tests/test_playbooks/fixtures/repository-3.yml, tests/test_playbooks/fixtures/repository-4.yml, tests/test_playbooks/fixtures/repository-5.yml, tests/test_playbooks/fixtures/repository-6.yml, tests/test_playbooks/fixtures/repository-7.yml, tests/test_playbooks/fixtures/repository-8.yml, tests/test_playbooks/fixtures/repository-9.yml, tests/test_playbooks/repository.yml, tests/test_playbooks/tasks/repository.yml
=> Add some parameters to repositories

plugins/modules/foreman_role.py, tests/test_playbooks/fixtures/role-0.yml, tests/test_playbooks/fixtures/role-1.yml, tests/test_playbooks/fixtures/role-10.yml, tests/test_playbooks/fixtures/role-11.yml, tests/test_playbooks/fixtures/role-2.yml, tests/test_playbooks/fixtures/role-3.yml, tests/test_playbooks/fixtures/role-4.yml, tests/test_playbooks/fixtures/role-5.yml, tests/test_playbooks/fixtures/role-7.yml, tests/test_playbooks/fixtures/role-8.yml, tests/test_playbooks/fixtures/role-9.yml, tests/test_playbooks/role.yml
=> Fix role filter analysis

README.md
=> Add Known issues section to the README

docs/testing.md, plugins/modules/foreman_auth_source_ldap.py, tests/test_playbooks/auth_source_ldap.yml, tests/test_playbooks/fixtures/auth_source_ldap-0.yml, tests/test_playbooks/fixtures/auth_source_ldap-1.yml, tests/test_playbooks/fixtures/auth_source_ldap-2.yml, tests/test_playbooks/fixtures/auth_source_ldap-3.yml, tests/test_playbooks/fixtures/auth_source_ldap-4.yml, tests/test_playbooks/fixtures/auth_source_ldap-5.yml, tests/test_playbooks/fixtures/auth_source_ldap-6.yml, tests/test_playbooks/tasks/auth_source_ldap.yml
This PR adds all the code to support the Netgroups checkbox that's available in the web GUI, but not here in ansible.
=> Add netgroups option to auth_source_ldap

plugins/modules/foreman_auth_source_ldap.py
=> auth_source_ldap: improve docs and add required_if for onthefly_register

tests/test_playbooks/fixtures/search_facts-0.yml, tests/test_playbooks/fixtures/search_facts-1.yml, tests/test_playbooks/fixtures/search_facts-2.yml, tests/test_playbooks/fixtures/search_facts-3.yml, tests/test_playbooks/fixtures/search_facts-4.yml, tests/test_playbooks/fixtures/search_facts-5.yml, tests/test_playbooks/fixtures/search_facts-6.yml, tests/test_playbooks/search_facts.yml, tests/test_playbooks/tasks/search_facts.yml, tests/test_playbooks/vars/search_facts.yml
=> add search_facts tests for organization and params

plugins/doc_fragments/foreman.py, plugins/modules/foreman_domain.py, plugins/modules/foreman_hostgroup.py, plugins/modules/foreman_installation_medium.py, plugins/modules/foreman_operatingsystem.py, plugins/modules/foreman_ptable.py, plugins/modules/foreman_subnet.py
=> Move nested parameter doc to fragment

tests/test_playbooks/repository.yml, tests/test_playbooks/tasks/repository.yml
=> make repository_url optional in tests

plugins/modules/katello_activation_key.py, tests/test_playbooks/activation_key.yml, tests/test_playbooks/fixtures/activation_key-0.yml, tests/test_playbooks/fixtures/activation_key-1.yml, tests/test_playbooks/fixtures/activation_key-10.yml, tests/test_playbooks/fixtures/activation_key-11.yml, tests/test_playbooks/fixtures/activation_key-12.yml, tests/test_playbooks/fixtures/activation_key-13.yml, tests/test_playbooks/fixtures/activation_key-14.yml, tests/test_playbooks/fixtures/activation_key-16.yml, tests/test_playbooks/fixtures/activation_key-17.yml, tests/test_playbooks/fixtures/activation_key-18.yml, tests/test_playbooks/fixtures/activation_key-19.yml, tests/test_playbooks/fixtures/activation_key-2.yml, tests/test_playbooks/fixtures/activation_key-20.yml, tests/test_playbooks/fixtures/activation_key-21.yml, tests/test_playbooks/fixtures/activation_key-22.yml, tests/test_playbooks/fixtures/activation_key-23.yml, tests/test_playbooks/fixtures/activation_key-25.yml, tests/test_playbooks/fixtures/activation_key-26.yml, tests/test_playbooks/fixtures/activation_key-27.yml, tests/test_playbooks/fixtures/activation_key-28.yml, tests/test_playbooks/fixtures/activation_key-29.yml, tests/test_playbooks/fixtures/activation_key-3.yml, tests/test_playbooks/fixtures/activation_key-4.yml, tests/test_playbooks/fixtures/activation_key-5.yml, tests/test_playbooks/fixtures/activation_key-6.yml, tests/test_playbooks/fixtures/activation_key-7.yml, tests/test_playbooks/fixtures/activation_key-8.yml, tests/test_playbooks/fixtures/activation_key-9.yml
Fixes: #630
includes #631 for simplicity :)
=> add override=default to k_activation_key

plugins/doc_fragments/foreman.py, plugins/module_utils/foreman_helper.py, plugins/modules/foreman_auth_source_ldap.py, plugins/modules/foreman_compute_resource.py, plugins/modules/foreman_domain.py, plugins/modules/foreman_environment.py, plugins/modules/foreman_hostgroup.py, plugins/modules/foreman_installation_medium.py, plugins/modules/foreman_job_template.py, plugins/modules/foreman_provisioning_template.py, plugins/modules/foreman_ptable.py, plugins/modules/foreman_role.py, plugins/modules/foreman_subnet.py, plugins/modules/foreman_user.py
=> move taxonomy handling to the helper

plugins/module_utils/foreman_helper.py
before:
No data found for label="rhel-8-for-x86_64-baseos-rpms"
after:
Found no results while searching for repository_sets with label="rhel-8-for-x86_64-baseos-rpms
=> improve the error when searching for resources

plugins/modules/foreman_host_power.py
=> host_power: Add support for foreman < 1.22

.github/workflows/release.yml
we need to run our `make dist` to generate a valid collection
=> fix releasing to galaxy

plugins/modules/foreman_user.py
=> require the mail parameter for creating a new user

requirements-dev.txt
see https://github.com/kevin1024/vcrpy/issues/504 for details
=> pin vcr to <4 until it's working properly

requirements-dev.txt
This reverts commit 4f7b295124b09cc3992ab4e684d9e25dedfc479e.
=> Revert "pin vcr to <4 until it's working properly (#668)"

plugins/modules/katello_repository_set.py
=> k_repository_set: only accept releasever and basearch for repositories

plugins/modules/katello_repository_set.py, tests/test_playbooks/fixtures/repository_set-0.yml, tests/test_playbooks/fixtures/repository_set-2.yml, tests/test_playbooks/fixtures/repository_set-3.yml, tests/test_playbooks/fixtures/repository_set-4.yml, tests/test_playbooks/fixtures/repository_set-5.yml, tests/test_playbooks/fixtures/repository_set-6.yml, tests/test_playbooks/fixtures/repository_set-7.yml, tests/test_playbooks/fixtures/repository_set-8.yml, tests/test_playbooks/repository_set.yml, tests/test_playbooks/tasks/repository_set.yml
=> allow to enable all repositories in a repo set

plugins/modules/katello_repository_set.py, tests/test_playbooks/fixtures/repository_set-0.yml, tests/test_playbooks/fixtures/repository_set-1.yml, tests/test_playbooks/fixtures/repository_set-10.yml, tests/test_playbooks/fixtures/repository_set-11.yml, tests/test_playbooks/fixtures/repository_set-12.yml, tests/test_playbooks/fixtures/repository_set-2.yml, tests/test_playbooks/fixtures/repository_set-3.yml, tests/test_playbooks/fixtures/repository_set-4.yml, tests/test_playbooks/fixtures/repository_set-5.yml, tests/test_playbooks/fixtures/repository_set-7.yml, tests/test_playbooks/fixtures/repository_set-8.yml, tests/test_playbooks/fixtures/repository_set-9.yml, tests/test_playbooks/repository_set.yml
=> purge empty substitutions

plugins/modules/katello_content_view.py
=> properly record unpublished compose content view data

plugins/modules/katello_repository_set.py
before we did use them for searching, but not in the resulting error
message, which can be confusing
=> use cleaned repository substitutions everywhere

Makefile, plugins/module_utils/foreman_helper.py
=> use subnets resource type for subnet6

plugins/modules/foreman_subnet.py, tests/test_playbooks/fixtures/subnet-20.yml
=> foreman_subnet: search domains by name

plugins/doc_fragments/foreman.py, plugins/module_utils/foreman_helper.py, plugins/modules/foreman_architecture.py, plugins/modules/foreman_compute_profile.py, plugins/modules/foreman_config_group.py, plugins/modules/foreman_hostgroup.py, plugins/modules/foreman_installation_medium.py, plugins/modules/foreman_job_template.py, plugins/modules/foreman_location.py, plugins/modules/foreman_operatingsystem.py, plugins/modules/foreman_provisioning_template.py, plugins/modules/foreman_role.py, plugins/modules/foreman_subnet.py, plugins/modules/foreman_user.py, plugins/modules/foreman_usergroup.py, plugins/modules/katello_activation_key.py, plugins/modules/katello_content_view.py, plugins/modules/katello_content_view_filter.py, plugins/modules/katello_content_view_version.py, plugins/modules/katello_repository.py, plugins/modules/katello_repository_set.py, plugins/modules/katello_sync_plan.py, tests/test_entity_spec_helper.py
Ansible's sanity tests got stricter around suboptions, so let's follow suite :)
=> argument_spec and documentation updates to please latest sanity checks

plugins/module_utils/foreman_helper.py, plugins/modules/katello_content_view_version.py
=> record CV version data when promoting

plugins/modules/redhat_manifest.py
also add a warning when redhat-uep.pem cannot be found
don't explicitly fail if it's not found, as the user might have it in
their global CA store, not as a separate file
Refs: #694
=> use redhat-uep.pem to validate subscription.rhn.redhat.com

plugins/modules/redhat_manifest.py, requirements.txt
Increase the fetch_url timeout in redhat_manifest to handle larger manifests that timeout on download.
=> Increase fetch_url timeout in redhat_manifest

tests/vcr_python_wrapper.py
=> Replace hostname in fixture writing

requirements-common.txt, requirements.txt
=> Fixes #709

plugins/modules/foreman_compute_resource.py
In foreman_azure_rm V2 some API endpoints have been changed.
tested with foreman-1.24.2  and foreman_azure_rm 2.0.7
=> add support for foreman_azure_rm v2

plugins/doc_fragments/foreman.py, plugins/module_utils/foreman_helper.py, plugins/modules/foreman_host.py, tests/test_playbooks/fixtures/host-0.yml, tests/test_playbooks/fixtures/host-1.yml, tests/test_playbooks/fixtures/host-10.yml, tests/test_playbooks/fixtures/host-11.yml, tests/test_playbooks/fixtures/host-12.yml, tests/test_playbooks/fixtures/host-13.yml, tests/test_playbooks/fixtures/host-15.yml, tests/test_playbooks/fixtures/host-16.yml, tests/test_playbooks/fixtures/host-17.yml, tests/test_playbooks/fixtures/host-18.yml, tests/test_playbooks/fixtures/host-19.yml, tests/test_playbooks/fixtures/host-2.yml, tests/test_playbooks/fixtures/host-20.yml, tests/test_playbooks/fixtures/host-21.yml, tests/test_playbooks/fixtures/host-22.yml, tests/test_playbooks/fixtures/host-3.yml, tests/test_playbooks/fixtures/host-4.yml, tests/test_playbooks/fixtures/host-5.yml, tests/test_playbooks/fixtures/host-6.yml, tests/test_playbooks/fixtures/host-7.yml, tests/test_playbooks/fixtures/host-8.yml, tests/test_playbooks/host.yml, tests/test_playbooks/tasks/host.yml
root pass is also added to hostgroup via the shared params.
=> add ip, mac, comment, owner and root_pass to host module

plugins/module_utils/foreman_helper.py, plugins/modules/foreman_hostgroup.py, plugins/modules/foreman_scc_account.py, plugins/modules/katello_activation_key.py, plugins/modules/katello_content_credential.py, plugins/modules/katello_content_view.py, plugins/modules/katello_host_collection.py, plugins/modules/katello_lifecycle_environment.py, plugins/modules/katello_product.py, plugins/modules/katello_sync_plan.py
while doing it, i realized, no katello module was using resolve_entities.
@bagasse maybe have a look?
=> Refactor mixins wrt organizations

plugins/modules/foreman_search_facts.py
otherwise you can't fetch full details from a katello resource
=> also pass params when fetching full details

plugins/inventory/foreman.py
diff against ansible-collection-migration/theforeman.foreman for `plugins/inventory/foreman.py` taking into account changes from #591
=> Check for missing commits vs devel for inventory plugin

plugins/modules/foreman_host.py, plugins/modules/foreman_subnet.py, tests/test_playbooks/tasks/host.yml
=> add missing provisioning params to foreman_host

plugins/module_utils/foreman_helper.py, plugins/modules/foreman_host.py, plugins/modules/foreman_hostgroup.py, tests/test_playbooks/fixtures/host-0.yml, tests/test_playbooks/fixtures/host-1.yml, tests/test_playbooks/fixtures/host-10.yml, tests/test_playbooks/fixtures/host-11.yml, tests/test_playbooks/fixtures/host-12.yml, tests/test_playbooks/fixtures/host-13.yml, tests/test_playbooks/fixtures/host-14.yml, tests/test_playbooks/fixtures/host-16.yml, tests/test_playbooks/fixtures/host-17.yml, tests/test_playbooks/fixtures/host-18.yml, tests/test_playbooks/fixtures/host-19.yml, tests/test_playbooks/fixtures/host-2.yml, tests/test_playbooks/fixtures/host-20.yml, tests/test_playbooks/fixtures/host-21.yml, tests/test_playbooks/fixtures/host-22.yml, tests/test_playbooks/fixtures/host-23.yml, tests/test_playbooks/fixtures/host-24.yml, tests/test_playbooks/fixtures/host-25.yml, tests/test_playbooks/fixtures/host-26.yml, tests/test_playbooks/fixtures/host-27.yml, tests/test_playbooks/fixtures/host-28.yml, tests/test_playbooks/fixtures/host-4.yml, tests/test_playbooks/fixtures/host-5.yml, tests/test_playbooks/fixtures/host-7.yml, tests/test_playbooks/fixtures/host-8.yml, tests/test_playbooks/fixtures/host-9.yml, tests/test_playbooks/host.yml
=> fix puppetclass support in foreman_host

plugins/doc_fragments/foreman.py, plugins/module_utils/foreman_helper.py, plugins/modules/foreman_scap_content.py, plugins/modules/foreman_scap_tailoring_file.py, tests/conftest.py, tests/fixtures/apidoc/scap_tailoring_file.json, tests/test_playbooks/data/ssg-firefox-ds-tailoring.xml, tests/test_playbooks/fixtures/scap_tailoring_file-0.yml, tests/test_playbooks/fixtures/scap_tailoring_file-1.yml, tests/test_playbooks/fixtures/scap_tailoring_file-2.yml, tests/test_playbooks/fixtures/scap_tailoring_file-3.yml, tests/test_playbooks/fixtures/scap_tailoring_file-4.yml, tests/test_playbooks/fixtures/scap_tailoring_file-5.yml, tests/test_playbooks/scap_tailoring_file.yml, tests/test_playbooks/tasks/scap_tailoring_file.yml
=>  add tailoring_file module

plugins/modules/katello_repository.py
=> Add http_proxy opts to repository

plugins/modules/katello_lifecycle_environment.py, tests/test_playbooks/fixtures/lifecycle_environment-0.yml, tests/test_playbooks/fixtures/lifecycle_environment-1.yml, tests/test_playbooks/fixtures/lifecycle_environment-10.yml, tests/test_playbooks/fixtures/lifecycle_environment-2.yml, tests/test_playbooks/fixtures/lifecycle_environment-3.yml, tests/test_playbooks/fixtures/lifecycle_environment-4.yml, tests/test_playbooks/fixtures/lifecycle_environment-7.yml, tests/test_playbooks/fixtures/lifecycle_environment-8.yml, tests/test_playbooks/fixtures/lifecycle_environment-9.yml, tests/test_playbooks/lifecycle_environment.yml, tests/test_playbooks/tasks/lifecycle_environment.yml
1/ `prior` was not resolved yet, so you would see an error accesing it
2/ on state=absent, entity is resolved thin, so there is no `label`
Fixes: #782
=> k_lifecycle_environment: don't fail when touching existing LCE

.github/workflows/docs.yml
=> don't fail committing when there is nothing to commit

docs/developing.md
Document lookup_entity, set_entity and scope_for as well as the special role of 'entity'.
=> Add documentation around lookup

plugins/modules/katello_content_view.py, tests/test_playbooks/tasks/content_view.yml
Added 'solve_dependencies' to 'content_view'
=> Added 'solve_dependencies' to 'content_view'

docs/developing.md
=> fix doc links after moving developing.md into the docs folder

Makefile
we have the variables loaded, so lets use them :)
=> use $(NAMESPACE) and $(NAME) instead of hardcoding them in the makefile

.github/workflows/docs.yml, .github/workflows/main.yml, .github/workflows/release.yml
this does set up the credentials for us automatically
=> use new checkout v2 action

plugins/modules/foreman_compute_resource.py
=> add proxmox to foreman_compute_resource

plugins/doc_fragments/foreman.py, plugins/module_utils/foreman_helper.py, tests/test_playbooks/tasks/katello_manifest.yml, tests/test_playbooks/tasks/setting_fact.yml
=> drop deprecated verify_ssl

.github/workflows/main.yml, plugins/module_utils/foreman_helper.py, plugins/modules/foreman_subnet.py, plugins/modules/katello_upload.py
=> Use 'missing_required_lib' to report import errors

plugins/modules/installation_medium.py, plugins/modules/job_template.py, plugins/modules/partition_table.py, plugins/modules/provisioning_template.py
and a fix in job template as it has no "layout"
=> better docs formatting

plugins/modules/hostgroup.py
=> Use required_by in hostgroup

plugins/modules/repository_sync.py
=> drop bad repository_sync example

galaxy.yml
=> release 1.0.0

plugins/modules/job_template.py, plugins/modules/partition_table.py, plugins/modules/provisioning_template.py
also don't use local_action, that's confusing
=> drop prefixes from the examples

galaxy.yml
waiting on https://github.com/theforeman/foreman-ansible-modules/pull/860
=> release 1.0.1

plugins/module_utils/foreman_helper.py, plugins/modules/bookmark.py, plugins/modules/compute_attribute.py, plugins/modules/content_view_version.py, plugins/modules/external_usergroup.py, plugins/modules/global_parameter.py, plugins/modules/image.py, plugins/modules/os_default_template.py, plugins/modules/repository.py, plugins/modules/scc_account.py, plugins/modules/snapshot.py
While thinking about the `ForemanStatelessEntityAnsibleModule` i found some cruft to cleanup...
=> Cleanup api

plugins/module_utils/foreman_helper.py
=> add > adds in docstring

Makefile
=> add requirements to dist

plugins/modules/http_proxy.py, tests/conftest.py, tests/fixtures/apidoc/http_proxy.json, tests/test_playbooks/fixtures/http_proxy-0.yml, tests/test_playbooks/fixtures/http_proxy-1.yml, tests/test_playbooks/fixtures/http_proxy-2.yml, tests/test_playbooks/fixtures/http_proxy-3.yml, tests/test_playbooks/fixtures/http_proxy-4.yml, tests/test_playbooks/fixtures/http_proxy-5.yml, tests/test_playbooks/fixtures/http_proxy-6.yml, tests/test_playbooks/fixtures/http_proxy-7.yml, tests/test_playbooks/fixtures/http_proxy-8.yml, tests/test_playbooks/fixtures/http_proxy-9.yml, tests/test_playbooks/http_proxy.yml, tests/test_playbooks/tasks/http_proxy.yml
=> add http_proxy module

.github/workflows/main.yml, Makefile
This should help when running `make sanity` while your venv python is not 3.7
=> Autodetect python version

docs/Makefile
in devel the tooling got revamped and can't be abused for our needs
currently
=> use stable-2.10 ansible branch for building docs

.github/workflows/main.yml
Includes #692 to see if stuff is green :)
=> test ansible/devel on Python 3.8
