theforeman/foreman-ansible-modules

modules/foreman_organization.py
While trying to be idempotent, the organziation module will fail if the
org is not present. This patch allows for that case. I am not sure how
the original code handled name changes, but this patch keeps that in tact.
=> Fix the organization module so that it can create the org.

modules/foreman_organization.py, modules/katello_content_view.py, modules/katello_product.py, modules/katello_publish.py, modules/katello_repository.py, modules/katello_sync.py, modules/katello_sync_plan.py, modules/katello_upload.py
Prior to this change, users had to double quote their inputs (i.e. `"\"Default Organization\""`). Now users don't need to know about that underlying difference. Just provide the string (i.e. `"Default Organization"`).
This logic will be moved to `module_utils` in a forthcoming PR.
=> Enclose search strings in quotes

modules/foreman_provisioning_template.py, modules/foreman_ptable.py
We (@mdellweg,@fobhep) added a functionality to foreman_ptable and foreman_provisioning_templates to perform bulk actions, i.e. updating or deleting all existing templates at once.
=> Add name='*' option to perform bulk actions on templates

modules/katello_activation_key.py
When we were mass-editing modules with check_mode, we introduced this regression.
```
*** AttributeError: 'NailGun' object has no attribute 'check_mode'
```
=> Check check_mode from self._module

modules/foreman_provisioning_template.py, modules/foreman_ptable.py
Using 'name: *' with 'state: present' to change the same option on all
templates is sensible, using it with 'state: present_with_default' is not,
because that will never change existing entities.
=> Fix changing bulk aktions in foreman_p{tabel,rovisioning_template}

modules/katello_content_view_version_promote.py
environment_ids was added fairly recently[1], `environment_id` has be around for a lot longer and enables us to use this module with older versions of Katello.
[1] https://github.com/Katello/katello/commit/506f569d8440640043bc7abdc20738b209cddbce
=> use environment_id instead of environment_ids for CV promote

Makefile, README.md, test/README.md, test/vcr_python_wrapper.py
This changes the `make test_<...>` rule so that for example composite_content_view tests do not run, when content_view tests are requested.
Also i started a small guideline about the test infrastructure.
=> Test playbooks

modules/katello_repository_set.py, modules/katello_sync_plan.py
Currently repo set is broken due to https://github.com/SatelliteQE/nailgun/issues/457#issuecomment-346649087 but there is a workaround on that issue.
=> document repo_set without release

modules/katello_sync_plan.py, requirements.txt, test/test_crud.py, test/test_playbooks/fixtures/sync_plan-1.yml, test/test_playbooks/fixtures/sync_plan-3.yml, test/test_playbooks/fixtures/sync_plan-5.yml, test/test_playbooks/sync_plan.yml, test/test_playbooks/tasks/global_parameter.yml, test/test_playbooks/tasks/sync_plan.yml
Should have been easy, but there is a problem around the date parsing.
py3 is ok, but py2 does not know how to interpret "%z" (for '+0100').
`Value of unknown type: <type 'exceptions.ValueError'>, 'z' is a bad directive in format '%Y/%m/%d %H:%M:%S %z'`
It is documented, though:
https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior
=> Add test for katello_sync_plan

.gitignore, ansible.cfg, test/test_crud.py
define the inventory location in the ansible.cfg for easier testing.
Also ignore pytest cache directories and prevent ansible from generating *.retry files as they aren't helpful here.
=> Set ansible inventory in ansible.cfg

test/test_playbooks/redhat_manifest.yml, test/test_playbooks/tasks/lifecycle_environment.yml, test/test_playbooks/tasks/redhat_manifest.yml
In conjunction with the reusable test_playbooks/tasks snippets using 'omit'
allows to really skip a parameter.
=> Use omit in tests

Makefile, module_utils/foreman_helper.py
Run pycodestyle also on module_utils. Fixed linting error.
=> Lint also module_utils

module_utils/foreman_helper.py
In some community templates, the erb comment with the metadata does not
start on the first line of the file. Therefore we should not use
re.match, but re.search to simply find the first erb comment block.
Fixes: #130
=> Fix finding comment in template

modules/katello_activation_key.py, test/test_playbooks/activation_key.yml, test/test_playbooks/fixtures/activation_key-1.yml, test/test_playbooks/fixtures/activation_key-3.yml, test/test_playbooks/fixtures/activation_key-5.yml, test/test_playbooks/fixtures/activation_key-7.yml, test/test_playbooks/fixtures/activation_key-9.yml, test/test_playbooks/tasks/activation_key_copy.yml
depends on https://github.com/SatelliteQE/nailgun/pull/517 and still needs tests
=> add support for copying activation keys

module_utils/ansible_nailgun_cement.py
for some reason the old version does not work with katello 3.4/satellite 6.3, even though the requests seem to be identical, as I did not have to re-record the VCRs.
:confused:
=> improve search for subscriptions

modules/redhat_manifest.py
Currently Katello also hardcodes this to sat-6.3, we should probably do the same.
https://github.com/Katello/katello/blob/master/app/models/katello/glue/provider.rb#L74
=> update redhat_manifest distributor_version

modules/foreman_setting.py, test/test_playbooks/tasks/setting.yml
Again, i have been up to a little experiment. Since we now have the new `naildown_entity`, we easily pass the returned information on.
=> Return the modified entity from setting module

modules/katello_activation_key.py
before we considered all results of the product content call as "current
overrides", even when they were not actually set to be overriden. this
resulted in too many "reset to default" calls (for overrides that
already were at "default") plus it made the module return changed=True
in too many cases.
let's only look at the entries that have a not None
enabled_content_override, which means they are actually overriden.
Fixes: #186
=> make content_overrides in k_activation_key truly idempotent

module_utils/ansible_nailgun_cement.py, modules/katello_content_view.py, modules/katello_content_view_publish.py, modules/katello_content_view_version.py, modules/katello_content_view_version_promote.py
This deprecates `katello_content_view_version_promote` & `katello_content_view_publish` modules in favour of a `katello_content_view_version` module. In addition to providing CCV publish and promote functionality this module also allows the removal of CVVs.
In future, we can extend this module to perform actions to a CVV, like `incremental_update`, `republish_repositories` & `export`.
----
I'll add some tests but wanted to get feedback on the approach first.
=> Add Content View Version module, deprecate dedicated publish & promote modules.

modules/katello_sync.py
=> repository param isnt required for katello_sync

module_utils/ansible_nailgun_cement.py, test/test_playbooks/content_view.yml, test/test_playbooks/fixtures/content_view-0.yml, test/test_playbooks/fixtures/content_view-1.yml, test/test_playbooks/fixtures/content_view-2.yml, test/test_playbooks/fixtures/content_view-3.yml
This fixes the case where multiple products have a repo with the same name (as repo name is unique only in the product scope). ATM the content view creation fail with 'repository_id has already been taken'.
=> Fix same repo name in different products in CV

README.md, module_utils/ansible_nailgun_cement.py, modules/foreman_subnet.py, requirements.txt, test/test_crud.py, test/test_playbooks/fixtures/subnet-0.yml, test/test_playbooks/fixtures/subnet-1.yml, test/test_playbooks/fixtures/subnet-2.yml, test/test_playbooks/fixtures/subnet-3.yml, test/test_playbooks/fixtures/subnet-4.yml, test/test_playbooks/fixtures/subnet-5.yml, test/test_playbooks/fixtures/subnet-6.yml, test/test_playbooks/fixtures/subnet-7.yml, test/test_playbooks/fixtures/subnet-8.yml, test/test_playbooks/subnet.yml, test/test_playbooks/subnet_vars.yml, test/test_playbooks/tasks/domain.yml, test/test_playbooks/tasks/subnet.yml
Add Subnets support.
I don't test smart_proxies integration, ATM, any comment/pointer are welcome on this part.
I've also modified `test/test_playbooks/tasks/domain.yml` to be able to test without DNS smart proxy on domains as it's not mandatory for domain creation and not required for testing domain dependent things like subnets.
When removing a subnet, if it's linked to domains, we have to unlink the subnet from all domains before (as done in tests). Any comments on this part are welcome too.
Requires [SatelliteQE/nailgun#570](https://github.com/SatelliteQE/nailgun/pull/570)
=> Add Subnets support

modules/foreman_search_facts.py
Currently, when using `foreman_search_facts` it defaults to None, this means if you don't specify a search param to the module it will send search="None" to the server. Which unless you have an entity named None it won't return anything.
=> default foreman_search_facts search param to an empty string

modules/katello_sync.py
The example for async katello_sync contained a misspelled var.
=> Fix name in katello_sync example

modules/katello_content_view.py
Hi all, thanks so much for adding functionality for Composite Content Views! While getting started, I was confused a bit by the documentation. 
In the documentation for the katello_content_view.py module, it was stated that the component option includes 'name', and either 'version' or 'latest'. However, looking at the code, what's expected is 'content_view', not name. 
Additionally, in the examples following the documentation string, 'name' appears instead of 'content_view'. However, the content_view option is still there, taking the arguments that should be given to 'version' in the first example component and 'latest' in the second component.
=> Fix documentation for creating a Composite CV

modules/foreman_compute_resource.py, test/test_crud.py, test/test_playbooks/compute_resource.yml, test/test_playbooks/fixtures/compute_resource-0.yml, test/test_playbooks/fixtures/compute_resource-1.yml, test/test_playbooks/fixtures/compute_resource-2.yml, test/test_playbooks/fixtures/compute_resource-3.yml, test/test_playbooks/fixtures/compute_resource-4.yml, test/test_playbooks/fixtures/compute_resource-5.yml, test/test_playbooks/fixtures/compute_resource-6.yml, test/test_playbooks/fixtures/compute_resource-7.yml, test/test_playbooks/fixtures/compute_resource-8.yml, test/test_playbooks/fixtures/compute_resource-9.yml, test/test_playbooks/tasks/compute_resource.yml
Refactoring compute_resource. Needs [Naigun PR#614](https://github.com/SatelliteQE/nailgun/pull/614) (merged)
* Deprecate compute resource specific params as direct module param `datacenter` in favor of nested hash `provider_params` for all provider specific params
* Deprecate `provider_auth` in favor of `provider_params`
* Add ability to change compute resource name
* Make `absent` state work even if provider is not set
* Refactor and add tests and make them usable as fixture from other tests (will be used for #222 tests)
=> Refactor compute_resource, improve tests

test/test_crud.py
If everything goes according to plan, pytest hides the output anyway.
If something goes wrong more informtion could be helpful.
=> Increase playbook verbosity in tests

modules/katello_content_credential.py, modules/katello_sync_plan.py
Updated the example to use the correct parameter `content_type` instead of `type`
=> Update katello_content_credential and katello_sync_plan example

plugins/modules/katello_manifest.py
I don't see any reason to be this restrictive, we can just ignore the param and allow people to write easier or more flexible roles/playbooks.
=> Remove vaildation for katello_manifest

requirements-common.txt
katello_sync_plan does not need these since 10960611a1d8fc27d0a56eb3682055b89808dd2f
=> don't require pytz and six

plugins/modules/foreman_auth_source_ldap.py, plugins/modules/foreman_compute_profile.py, plugins/modules/foreman_domain.py, plugins/modules/foreman_environment.py, plugins/modules/foreman_installation_medium.py, plugins/modules/foreman_role.py, plugins/modules/foreman_subnet.py, plugins/modules/katello_lifecycle_environment.py, plugins/modules/katello_manifest.py, plugins/modules/katello_repository_set.py, plugins/modules/redhat_manifest.py
I think examples should be as minimal as possible
=> don't add validate_certs: True/False to the examples

plugins/modules/katello_repository_set.py
RHEL 8 repos won't enable properly if an arch is specified. This change demonstrates how to enable the BaseOS release version 8 repository.
=> Add example for enabling RHEL 8 repo

.mailmap
this should allow "git shortlog" to summarize the authors properly
=> add mailmap file

docs/Makefile
Ansible changed their doc building tooling in https://github.com/ansible/ansible/commit/019d078a5a457823e8d445d4e949b5ed041e2609
This commit ensures that we can build our docs for now. We should port
our build process to the new tooling at some point, though.
=> use ansible 2.8 not devel for building docs

plugins/modules/katello_repository.py
Hi,
the URL parameter is not mandatory when modifying an existing repository. Not sure whether it's mandatory otherwise. 
WDYT?
=> Correct documentation

tests/test_playbooks/fixtures/repository_set-0.yml, tests/test_playbooks/fixtures/repository_set-1.yml, tests/test_playbooks/fixtures/repository_set-2.yml, tests/test_playbooks/fixtures/repository_set-3.yml, tests/test_playbooks/fixtures/repository_set-4.yml, tests/test_playbooks/repository_set.yml, tests/test_playbooks/tasks/repository_set.yml
this adds a setup/teardown step and creates an org and manifest (no
manifest, no subs, no reposets)
=> make katello_repository_set tests reproducible

tests/vcr_python_wrapper.py
this allows to record against Foreman running in a non-prod setup
=> don't match scheme and port in VCR

plugins/module_utils/foreman_helper.py, plugins/modules/foreman_installation_medium.py, plugins/modules/foreman_user.py
When using the alias, is is left in the module parameters, thus failing the
validation with affects_multiple.
=> Remove alias 'verify_ssl' from cleaned parameters

plugins/modules/foreman_compute_attribute.py, plugins/modules/foreman_compute_profile.py
Instead of `vm_attrs`, `vm_attributes` can be used.
While porting from a playbook using `ansible_module_foreman`, it became obvious, that this would be a very handy alias.
=> Add alias to vm_attrs

tests/vcr_python_wrapper.py
this should allow us to use compressed requests while still keeping
readable (uncompressed) tapes
=> set decode_compressed_response=True in VCR options

plugins/modules/foreman_subnet.py, requirements-common.txt
this has the benefit that we don't need any external libraries on
python3
=> use ipaddress instead of netaddr

requirements-common.txt
this is only needed when the module runs on a different node than
ansible, which should be seldom, but possible
=> add PyYAML to requirements

Makefile, plugins/filter/foreman.py, plugins/modules/foreman_host_power.py, plugins/modules/katello_activation_key.py, plugins/modules/redhat_manifest.py, requirements-dev.txt, tests/vcr_python_wrapper.py
flake uses pycodestyle internally, so we getting a superset of checks
and don't ignore E722 anymore, we fixed that
=> use flake8 instead of pycodestyle for linting

plugins/module_utils/foreman_helper.py
This maintains the original attributes such as `__name__` and `__doc__` which are useful in introspection.
=> Use functools.wraps in _exception2fail_json

plugins/module_utils/foreman_helper.py, plugins/modules/foreman_domain.py
this adds diff output when ansible is called with --diff
create:
--- before
+++ after
@@ -1 +1,7 @@
-{}
+{
+    "fullname": "three.example",
+    "id": 13,
+    "location_ids": [],
+    "name": "three.example.net",
+    "organization_ids": []
+}
fixtures | CHANGED => {
"changed": true, 
"entity": {
"created_at": "2019-09-20 07:34:22 UTC", 
"dns": null, 
"dns_id": null, 
"fullname": "three.example", 
"id": 13, 
"interfaces": [], 
"locations": [], 
"name": "three.example.net", 
"organizations": [], 
"parameters": [], 
"subnets": [], 
"updated_at": "2019-09-20 07:34:22 UTC"
}
}
update:
--- before
+++ after
@@ -1,5 +1,5 @@
{
-    "fullname": "three",
+    "fullname": "three.example",
"id": 12,
"location_ids": [],
"name": "three.example.net",
fixtures | CHANGED => {
"changed": true, 
"entity": …
=> diff support

plugins/module_utils/foreman_helper.py
otherwise the code will go into a deep recursion because the API returns
a foreman_task and then we wait for that to finish, query it, get a
task, and so on.
Fixes: #502
=> make foreman_tasks show asynchronous

plugins/modules/katello_sync.py
30 minutes is too short for a full repo sync sometimes, let's wait for 2
hours.
in the old (nailgun) code this was set to "180000", which we translated
to 30 minutes, but nailgun in reality takes seconds too, so the old code
really waited up to 50 hours.
=> increase the sync timeout

tests/vcr_python_wrapper.py
filter_headers is only applied to requests, not to responses, so we have
to filter ourself
=> really don't record the apipie checksum

plugins/module_utils/foreman_helper.py
this should fix katello modules doing a find_resource(organization)
before looking for the real resource
=> don't store thin results as _before

README.md
=> document that mazer is for 2.8 and ansible-galaxy is for 2.9+

plugins/modules/foreman_role.py, tests/test_playbooks/fixtures/role-0.yml, tests/test_playbooks/fixtures/role-1.yml, tests/test_playbooks/fixtures/role-2.yml, tests/test_playbooks/fixtures/role-3.yml, tests/test_playbooks/fixtures/role-4.yml, tests/test_playbooks/fixtures/role-5.yml, tests/test_playbooks/fixtures/role-6.yml, tests/test_playbooks/role.yml, tests/test_playbooks/tasks/role.yml
As proposed here https://github.com/theforeman/foreman-ansible-modules/pull/293, this PR adds management of Role Filters inside Role directly. It doesn't support overriding locations or organizations, which can be added at later point.
Note that this implementation basically re-adds all filters everytime. My assumption is that it is simpler (from code perspetive) and more performant than comparing all existing and yaml filters one by one, but I am open for suggestions if this implementation is not good enough.
=> Add filters support for roles.

plugins/module_utils/foreman_helper.py, plugins/modules/foreman_host_power.py, plugins/modules/katello_activation_key.py, plugins/modules/katello_repository_set.py
some calls are read only, but we don't use the find/list wrappers
because the api is weird. let's allow these.
otherwise e.g. katello_activation_key is broken in check mode when
trying to assign content overrides
=> allow certain resource_action calls in check_mode

.gitignore, plugins/modules/foreman_operatingsystem.py
This PR:
- Resolves #550 
- Adds required parameters as per the API calls
- Adds `.idea` into `.gitignore` for Pycharm users.
When making the API call without any one of the `name`, `major`, `family` and `pw_hash` parameters, the call fails. Consequently, they are marked as required=True.
=> Improve docs and fix required parameters

plugins/modules/foreman_search_facts.py
This PR adds the `params` option to the `foreman_search_facts` module. It resolves #523 as well as #338 .
WDYT?
This seems to work with the `subscriptions` resources, which requires org_id as an extra parameter.
=> Provide a way to pass parameters to the search_facts module

plugins/module_utils/foreman_helper.py, plugins/modules/katello_activation_key.py, plugins/modules/katello_content_view.py, plugins/modules/katello_repository_set.py, plugins/modules/katello_sync_plan.py, tests/test_playbooks/activation_key.yml, tests/test_playbooks/content_view.yml, tests/test_playbooks/domain.yml, tests/test_playbooks/repository_set.yml, tests/test_playbooks/sync_plan.yml, tests/test_playbooks/tasks/activation_key.yml, tests/test_playbooks/tasks/content_view.yml, tests/test_playbooks/tasks/domain.yml, tests/test_playbooks/tasks/repository_set.yml, tests/test_playbooks/tasks/sync_plan.yml
this only changes the AK module, if the design is ok, I'll update the following modules too:
* katello_content_view
* katello_repository_set
* katello_sync_plan
=> modules that call resource_action can also record before/after state

plugins/modules/foreman_subnet.py
Module: foreman_subnet
API Url: https://theforeman.org/api/1.23/apidoc/v2/subnets/create.html
This PR adds a new option: `template_proxy`.
Let me know if I forgot something.
=> Foreman_subnet: add template_proxy option

plugins/modules/foreman_subnet.py
Module: foreman_subnet
API Url: https://theforeman.org/api/1.23/apidoc/v2/subnets/create.html
This PR adds a new choice "None" for the IPAM option.
Let me know if I forgot something.
=> Foreman_subnet: add IPAM choice None

plugins/modules/foreman_compute_profile.py, plugins/modules/foreman_compute_resource.py
This PR fixes the wrong value of "server_type" in the examples of the following modules:
- foreman_compute_profile
- foreman_compute_resource
This will prevent the following error from occurring when users enter an FQDN in server_url without prefixing it with "http://" or "https://"
`    "msg": "Failed to connect to Foreman server: Could not load data from foreman.example.com: Invalid URL '/apidoc/v2.json': No schema supplied. Perhaps you meant http:///apidoc/v2.json?\n                  - is your server down?\n                  - was rake apipie:cache run when using apipie cache? (typical production settings) "
`
=> Fix wrong value in the examples for "server_url"

plugins/modules/foreman_hostgroup.py, tests/test_playbooks/hostgroup.yml
Fixes #526 
Could not write tests using any of the public mock repos. Need something like RHEL's kickstart to enable "synced content" option on "Operating System" tab. If anyone hints how to - I'd be happy to add tests.
For Satellite/RHEL this would be quite a common use case.
=> add kickstart_repository option to hostgroup

Makefile
we don't distribute tests and stuff in the collection anyways
Fixes: #496
=> remove links to devel docs from the collection README

plugins/module_utils/foreman_helper.py, plugins/modules/foreman_search_facts.py
when using a Katello module against a non-Katello setup, this will now
error:
localhost | FAILED! => {
"changed": false,
"msg": "Failed to connect to Foreman server: The server does not seem to have the Katello plugin installed. "
}
and on any other missing plugin:
localhost | FAILED! => {
"changed": false,
"msg": "Failed to list resource: The server doesn't know about products, is the right plugin installed?"
}
Fixes: #493
=> nicer errors when plugin resources are not found

plugins/modules/foreman_compute_attribute.py, plugins/modules/foreman_job_template.py
doc-required-mismatch errors was introduced in https://github.com/ansible/ansible/commit/4be8b2134f0f6ed794ef57a621534f9561f91895
=> correct required attributes spotted by ansible-test sanity

plugins/modules/katello_repository_set.py
users might enter numbers, but the API will always expect them as strings
=> force repository substitutions to be strings

plugins/modules/katello_repository_set.py
this for example happens when the user entered more substitutions than
the repo provides.
also adjust the error message in the case we desire more than we have as
`name` is not always available
Refs: #355
Refs: #453
=> add a warning when no desired repos were found for a repo_set

plugins/modules/katello_activation_key.py, tests/test_playbooks/fixtures/activation_key-10.yml, tests/test_playbooks/fixtures/activation_key-11.yml, tests/test_playbooks/fixtures/activation_key-7.yml, tests/test_playbooks/fixtures/activation_key-8.yml, tests/test_playbooks/fixtures/activation_key-9.yml
To check the existing content overrides of an activation key, we need to
search in all products and not just those provided by the subscription(s). Otherwise, in case of an AK with auto-attach = True and without subscription we are
missing the already defined content overrides.
Fixes #688
PS: According to the documentation this parameter has been added in katello 3.5. I'm not sure if  older versions will silently ignore it or fail
=> Search content_overrides in all products for activation key creation

plugins/modules/foreman_hostgroup.py
point out that this is required for the synced content feature (as
that's the name people see in the UI)
also wrap other params better
=> improve hostgroup docs around kickstart_repository parameter

plugins/modules/foreman_operatingsystem.py
Include Base64 and Base64-Windows for password_hash.
These are missing if using Windows. Please add them and commit to next RPM, etc. releases.
=> Include Base64 and Base64-Windows for password_hash

plugins/callback/foreman.py
Tested on top of https://github.com/theforeman/foreman-ansible-modules/pull/718 by running the sanity tests and
```
ANSIBLE_COLLECTIONS_PATHS=../../.. ansible-doc -t callback theforeman.foreman.foreman
```
from discussion in https://github.com/theforeman/foreman-ansible-modules/pull/591, the PR for the inventory plugin
Put into 2 commits to separate the file exactly as it was in Ansible core versus modifications that I made.
=> Migrate foreman callback plugin to this collection

plugins/modules/katello_repository_set.py
before:
```
Desired repositories are not available on the repository set product: {'id': 363} label: rhel-7-server-rhv-4.2-manager-rpms.
Searched: [{'basearch': 'x86_64', 'releasever': '7Server'}]
Found: set()
Available: {'Red Hat Virtualization Manager v4.2 RHEL 7 Server RPMs x86_64'}
```
after:
```
Desired repositories are not available on the repository set product: Red Hat Virtualization Manager label: rhel-7-server-rhv-4.2-manager-rpms.
Searched: {'product': 'Red Hat Virtualization Manager', 'label': 'rhel-7-server-rhv-4.2-manager-rpms', 'repositories': [{'basearch': 'x86_64', 'releasever': '7Server'}]}
Found: set()
Available: [{'name': 'Red Hat Virtualization Manager v4.2 RHEL 7 Server RPMs x86_64', 'repositories': {'basearch': 'x86_64'}}]
```
also improved the "found" part:
before: …
=> improve repo_set error when it can't find a set

docs/developing.md, plugins/module_utils/foreman_helper.py, plugins/modules/foreman_hostgroup.py, plugins/modules/foreman_scc_account.py, plugins/modules/foreman_scc_product.py, plugins/modules/foreman_snapshot.py, plugins/modules/foreman_subnet.py
this PR adds `required_plugins` as a parameter to `ForemanAnsibleModule`, which allows individual modules to express a dependency on Foreman plugins, either for the whole module, or for individual parameters.
the syntax is:
```python
required_plugins=[
('plugin_name', ['list', 'of', 'params']),
('plugin_name', ['*']),
]
```
Fixes: #728
=> add required_plugins to ForemanAnsibleModule

plugins/modules/katello_content_view_filter.py, tests/test_playbooks/tasks/content_view_filter_package.yml
It appears that this was just missed since the `content_filter_rule_rpm_spec` already included `architecture`.
=> added 'architecture' to 'content_view_filter'

plugins/modules/foreman_search_facts.py
Update examples for foreman_search_facts module to:
- Fix `with_items` variable format
- Highlight which examples relate specifically to Katello facts
- Changes first example to search for a fact that doesn't default to potentially null value (http_proxy) in a fresh foreman installation.
Fixes #762
=> Search facts documentation

.github/workflows/docs.yml
master does not exist in an action as it checks out the commit directly
=> use origin/master not master when fetching the templates

plugins/modules/foreman_operatingsystem.py, plugins/modules/foreman_os_default_template.py
- Updates operatingsystem creation examples as they can't contain spaces.
- Description of operatingsystem attribute for os_default_template which can be an operating system `name` or `title` (title being name and major version). Using just the name when multiple operating systems exist with the same name (but different versions) results in an error when trying to create a template association.
=> Update documentation for operatingsystem and os_default_template modules

plugins/modules/foreman_templates_import.py
with the | it just renders the first line as a note
=> fix notes rendering in templates_import module

plugins/inventory/foreman.py
This PR adds two features:
- host_filters: This is backward compatible with the script for filtering hosts
- want_ansible_ssh_host: This is backward compatible with script to add ip address of the node as a ansible_ssh_host  hostvars.
Both of these were present in the script:
https://github.com/ansible-collections/community.general/blob/ce9701f813c3b8d8171ce7272ae15be5dbb7fd37/scripts/inventory/foreman.ini#L133
https://github.com/ansible-collections/community.general/blob/ce9701f813c3b8d8171ce7272ae15be5dbb7fd37/scripts/inventory/foreman.ini#L193
=> add host_filters and want_ansible_ssh_host like script used to have

plugins/modules/redhat_manifest.py
the module interacts with the Red Hat portal, not Foreman
=> correct the doc strings of redhat_manifest

.github/workflows/main.yml, Makefile, requirements-common.txt, tests/test_crud.py, tests/test_module_state.py
ansible devel is now called ansible-base and that seems to confuse some
pythons
=> don't pass egg name when installing ansible

plugins/modules/subnet.py, tests/test_playbooks/subnet.yml
fixes: #878
Additional benefit: You can absent the subnet without mask or cidr.
=> Require mask/cidr only on ipv4

plugins/inventory/foreman.py
Ability to control the number of hosts returned per page which can be definitely useful some users.
Result on Foreman:
```
192.168.169.112 - - [03/Jul/2020:18:00:37 -0400] "GET //api/v2/hosts/3?page=1&per_page=500 HTTP/1.1" 200 2814 "-" "python-requests/2.24.0"
192.168.169.112 - - [03/Jul/2020:18:00:37 -0400] "GET //api/v2/hosts/3?page=1&per_page=500 HTTP/1.1" 200 2814 "-" "python-requests/2.24.0"
192.168.169.112 - - [03/Jul/2020:18:00:38 -0400] "GET //api/v2/hosts/2?page=1&per_page=500 HTTP/1.1" 200 2821 "-" "python-requests/2.24.0"
192.168.169.112 - - [03/Jul/2020:18:00:38 -0400] "GET //api/v2/hosts/2?page=1&per_page=500 HTTP/1.1" 200 2821 "-" "python-requests/2.24.0"
192.168.169.112 - - [03/Jul/2020:18:00:38 -0400] "GET //api/v2/hosts/5?page=1&per_page=500 HTTP/1.1" 200 2796 "-" …
```
=> Ability to control the number of hosts returned per page

plugins/callback/foreman.py
When ansible fails to connect to remote host,
callback sends a report to Foreman without
any indication that the report comes from
Ansible. As a result, Foreman is unable
to determine the report origin.
This adds a 'reporter' attribute into
the logs that are sent.
Fixes #836
=> Add reporter to report logs sent by foreman callback
